import { test } from 'node:test'
import assert from 'node:assert/strict'
import { build } from 'esbuild'
import { fileURLToPath } from 'node:url'
const root=fileURLToPath(new URL('../../',import.meta.url))
const compiled=await build({entryPoints:[`${root}src/client/model.js`],bundle:true,write:false,platform:'node',format:'esm',alias:{'@omnimux/form-contract':`${root}../../packages/form-contract/src/index.ts`}})
const {createEditor}=await import(`data:text/javascript;base64,${Buffer.from(compiled.outputFiles[0].text).toString('base64')}`)
const definition={protocolVersion:1,id:'test',templateVersion:'1.0.0',title:'test',description:'test',examples:[{ref:'x',title:'x',kind:'video'}],fields:[{id:'name',type:'text',label:'name',required:true},{id:'file',type:'file',label:'file',required:true,accept:['video/*'],maxFiles:1,maxBytes:100}],prompt:'Do {{name}}',attachments:['file']}
const file={assetId:'id',name:'a.mp4',mimeType:'video/mp4',sizeBytes:1}
const values={name:'test',file:[{ref:'id',name:'a.mp4',mimeType:'video/mp4',sizeBytes:1}]}
function setup(opts={}) { let revision=0,calls=[]; const hub={resolveFiles:async()=>[file],importFile:async()=>file,prepareDraft:async a=>{calls.push(a);return {ok:true,sessionId:'s'}},...opts.hub}; const request=opts.request??(async(k,b)=>b?{draft:{revision:++revision}}:{draft:{values,revision:0},otherVersions:[]});const editor=createEditor({definition,workspaceId:'w',hub,request,uuid:()=>`r${Math.random()}`});return {editor,calls,hub} }
test('restores and revalidates refs; blocks stale files before creating a session',async()=>{const {editor,calls}=setup({hub:{resolveFiles:async()=>{throw Error('gone')}}});await editor.load();assert.deepEqual(editor.getSnapshot().staleRefs,['id']);await editor.submit();assert.equal(calls.length,0);editor.dispose()})
test('double click shares in-flight submission; retry preserves request id after timeout',async()=>{let release,attempt=0;const {editor,calls,hub}=setup();hub.prepareDraft=async a=>{calls.push(a);attempt++;if(attempt===1){await new Promise(r=>release=r);return {ok:false,error:'timeout'}}return {ok:true,sessionId:'s'}};await editor.load();const first=editor.submit();await new Promise(r=>setTimeout(r,0));await editor.submit();assert.equal(calls.length,1);release();await first;await editor.submit();assert.equal(calls[0].requestId,calls[1].requestId);assert.equal(editor.getSnapshot().success,'s');editor.dispose()})
test('late import after removal or disposal never repopulates values',async()=>{let release;const {editor}=setup({hub:{importFile:()=>new Promise(r=>release=r)}});await editor.load();editor.removeAttachment('file','id');await editor.importFiles(definition.fields[1],[{name:'x',size:1}]);const upload=editor.getSnapshot().uploads[0];editor.removeUpload(upload.id);release(file);await new Promise(r=>setTimeout(r,0));assert.deepEqual(editor.getSnapshot().values.file,[]);editor.dispose()})
test('save failures retain edits and prevent session creation',async()=>{const {editor,calls}=setup({request:async(k,b)=>{if(b)throw Error('disk unavailable');return {draft:{values,revision:0},otherVersions:[]}}});await editor.load();editor.set('name','changed');await editor.submit();assert.equal(editor.getSnapshot().values.name,'changed');assert.equal(calls.length,0);assert.match(editor.getSnapshot().notice,/disk/);editor.dispose()})
test('corrupt restoration fails closed and cannot overwrite original',async()=>{const {editor,calls}=setup({request:async()=>{throw Error('corrupt')}});await editor.load();editor.set('name','lost');await editor.submit();assert.equal(editor.getSnapshot().invalid,true);assert.equal(calls.length,0);editor.dispose()})
test('changed prompt creates fresh id and reset retains template defaults',async()=>{const {editor,calls}=setup();await editor.load();await editor.submit();editor.set('name','next');await editor.submit();assert.notEqual(calls[0].requestId,calls[1].requestId);await editor.reset();assert.deepEqual(editor.getSnapshot().values,{});editor.dispose()})

test('malformed restored field data stays preserved until explicit reset',async()=>{let writes=0;const {editor}=setup({request:async(k,b)=>{if(b){writes++;return {draft:{revision:1}}}return {draft:{revision:0,values:{name:{unexpected:true},file:[]}},otherVersions:[]}}});await editor.load();assert.equal(editor.getSnapshot().restoreInvalid,true);editor.set('name','replacement');await editor.submit();assert.equal(writes,0);await editor.reset();assert.equal(writes,1);assert.equal(editor.getSnapshot().restoreInvalid,false);editor.dispose()})
