export const GXGEN_NEW_HOOKS = [
  {
    id: "gxgen-hook-01-epic-fail",
    categorySlug: "creative-stunt",
    categoryName: "Creative Stunt",
    categoryNameZh: "创意特技与翻车",
    title: "Epic Fail",
    titleZh: "史诗级翻车反差",
    description: "A person performs an unsuccessful backflip, falls, and immediately begins an unflappable review.",
    prompt: "Scene: Outdoor park, backyard, or gym setting with natural daylight.\nOpening: A person attempts an ambitious stunt or backflip, fails awkwardly, crashes to the ground, and without a second of hesitation or embarrassment, pulls the product out and starts an unflappable, deadpan review.\nRhythm: Fast action attempt (0-1s) -> sudden comedic fail (1-2s) -> deadpan recovery with product directly to camera (2-3s).\nTexture: Raw handheld camera, natural ambient sound with thud impact, comedic timing, immediate viewer hook.",
    durationSeconds: 3,
    videoPath: "hooks/creative-stunt/gxgen_epic_fail.mp4",
    posterPath: "hooks/creative-stunt/gxgen_epic_fail_poster.jpg"
  },
  {
    id: "gxgen-hook-02-product-hit",
    categorySlug: "creative-stunt",
    categoryName: "Creative Stunt",
    categoryNameZh: "创意特技与击中",
    title: "Product Hit",
    titleZh: "产品空投击中",
    description: "Object flies into frame, hits subject. Brief reaction -> pivot to product.",
    prompt: "Scene: A clean living room, kitchen, or desk space.\nOpening: The hero product flies into frame unexpectedly, lightly bonking the subject on the shoulder or arm. The person gasps, pauses for a microsecond, then looks down at the product in awe and immediately pivots into showcasing its benefits.\nRhythm: Sudden airborne motion -> light comic impact -> sharp pivot to clear product value proposition.\nTexture: Punchy sound effect, crisp lighting, high engagement rate, scroll-stopping interruption.",
    durationSeconds: 3,
    videoPath: "hooks/creative-stunt/gxgen_product_hit.mp4",
    posterPath: "hooks/creative-stunt/gxgen_product_hit_poster.jpg"
  },
  {
    id: "gxgen-hook-03-spicy-macro",
    categorySlug: "macro-reveal",
    categoryName: "Macro Reveal",
    categoryNameZh: "微距特写揭秘",
    title: "Spicy Macro Tilt",
    titleZh: "微距特写慢摇",
    description: "Extreme close-up of collarbone, tilts up to reveal flawless look, before product pitch.",
    prompt: "Scene: Studio vanity mirror or soft golden hour interior.\nOpening: Extreme macro close-up of collarbone or skin texture, slowly tilting upward to reveal a radiant, flawless look, transitioning into a natural selfie angle before transitioning directly into the hero product pitch.\nRhythm: Slow sensual macro glide (0-1.5s) -> upward tilt and eye contact (1.5-2.5s) -> product showcase.\nTexture: Dreamy natural bokeh, premium skin glow, intimate acoustic cue, high beauty conversion.",
    durationSeconds: 3,
    videoPath: "hooks/macro-reveal/gxgen_spicy_macro.mp4",
    posterPath: "hooks/macro-reveal/gxgen_spicy_macro_poster.jpg"
  },
  {
    id: "gxgen-hook-04-random-mic",
    categorySlug: "absurd-vlog",
    categoryName: "Absurd Vlog",
    categoryNameZh: "无厘头街头互动",
    title: "Random Object Mic",
    titleZh: "随机物品变麦克风",
    description: "Absurd object falls into person's hand, immediately used as a microphone for a serious review.",
    prompt: "Scene: Casual street vlog or walking shot in a sunny city.\nOpening: While talking to camera, a totally random absurd object (a baguette, a massive whisk, a toy) drops from above into the person's hand. Without missing a beat, they bring it to their mouth like a news mic and keep pitching the product seriously.\nRhythm: Casual talking -> sudden absurd catch -> straight-faced product value delivery.\nTexture: Fast vlog cadence, street ambient chatter, dry deadpan humor, instant comments driver.",
    durationSeconds: 3,
    videoPath: "hooks/absurd-vlog/gxgen_random_mic.mp4",
    posterPath: "hooks/absurd-vlog/gxgen_random_mic_poster.jpg"
  },
  {
    id: "gxgen-hook-05-street-interview",
    categorySlug: "street-interview",
    categoryName: "Street Interview",
    categoryNameZh: "街头采访转折",
    title: "Street Interview Pivot",
    titleZh: "街头无厘头采访",
    description: "Interviewer asks stranger a random question, confusion builds until naturally pivoting into the product.",
    prompt: "Scene: Busy downtown pedestrian street, handheld mic framing.\nOpening: An interviewer asks a random passerby an unexpected, bizarre question based on a previous stranger's answer. As mild confusion builds, the second person notices the hero product, eyes lighting up, leading into an authentic spontaneous review.\nRhythm: Rapid question -> bewildered reaction -> sudden organic spotlight on the product.\nTexture: True vox-pop handheld aesthetic, authentic audio, relatable social proof.",
    durationSeconds: 3,
    videoPath: "hooks/street-interview/gxgen_street_interview.mp4",
    posterPath: "hooks/street-interview/gxgen_street_interview_poster.jpg"
  },
  {
    id: "gxgen-hook-06-product-crash",
    categorySlug: "destruction-reset",
    categoryName: "Destruction & Reset",
    categoryNameZh: "破坏与瞬间复原",
    title: "Product Crash & Restore",
    titleZh: "产品坠落重构",
    description: "Product falls and destroyed creating chaos; harsh sharpness snaps into perfectly clean review.",
    prompt: "Scene: Sleek tabletop or modern kitchen counter.\nOpening: The product falls from high above and crashes into pieces with dramatic dust and sound. A quick cut sound effects boom snaps the scene into a pristine, spotless version where the presenter calmly picks it up unharmed.\nRhythm: Catastrophic drop (0-1s) -> audio snap reset (1.2s) -> spotless product hero showcase.\nTexture: Bass drop transition, high contrast visual snap, satisfying shock-and-relief hook.",
    durationSeconds: 3,
    videoPath: "hooks/destruction-reset/gxgen_product_crash.mp4",
    posterPath: "hooks/destruction-reset/gxgen_product_crash_poster.jpg"
  },
  {
    id: "gxgen-hook-07-blizzard-test",
    categorySlug: "extreme-durability",
    categoryName: "Extreme Durability",
    categoryNameZh: "极端环境耐候测试",
    title: "Blizzard Stress Test",
    titleZh: "室内暴风雪极限测试",
    description: "Cozy indoor scene hit by violent blizzard, chaos fills room but product stays intact and working.",
    prompt: "Scene: A cozy, warm living room or coffee nook.\nOpening: A sudden impossible indoor blizzard blasts through the room blowing papers and clothes away, but the hero product stays unmoved, glowing and functioning flawlessly amidst the swirling frost.\nRhythm: Cozy calm -> sudden violent storm gust -> rock-solid product resilience spotlight.\nTexture: Wind howling SFX, flying particles, cinematic cold-vs-warm grade, powerful durability proof.",
    durationSeconds: 3,
    videoPath: "hooks/extreme-durability/gxgen_blizzard_test.mp4",
    posterPath: "hooks/extreme-durability/gxgen_blizzard_test_poster.jpg"
  },
  {
    id: "gxgen-hook-08-camera-bump",
    categorySlug: "breaking-fourth-wall",
    categoryName: "Breaking Fourth Wall",
    categoryNameZh: "打破第四面墙",
    title: "Camera Bump Reveal",
    titleZh: "镜头撞击意外转折",
    description: "Camera operator accidentally bumps into person, who recovers and naturally reveals the product.",
    prompt: "Scene: Walk-and-talk lifestyle setting.\nOpening: The camera person physically bumps into the creator's forehead, shaking the frame vigorously. The creator rubs their head with a laugh, turns toward the camera, and naturally points to the product they are holding as the conversation starter.\nRhythm: Shaky impact collision -> organic laugh and recovery -> natural product entry.\nTexture: In-camera bump effect, genuine smile, unpolished high-trust vlog energy.",
    durationSeconds: 3,
    videoPath: "hooks/breaking-fourth-wall/gxgen_camera_bump.mp4",
    posterPath: "hooks/breaking-fourth-wall/gxgen_camera_bump_poster.jpg"
  },
  {
    id: "gxgen-hook-09-product-dodge",
    categorySlug: "ninja-reaction",
    categoryName: "Ninja Reaction",
    categoryNameZh: "高能反应抓物",
    title: "Product Dodge Catch",
    titleZh: "高燃闪避接物",
    description: "Product flies at person's face; they dodge quickly, standing up straight holding it calmly to review.",
    prompt: "Scene: Minimalist studio or modern gym.\nOpening: An item shoots toward the subject's face at high speed. The person performs a swift, athletic dodge, catches the object cleanly out of the air, and stands tall, presenting the hero product with total composure.\nRhythm: High-speed projectile -> split-second athletic dodge/catch -> rock-solid hero freeze.\nTexture: Whoosh sound, athletic precision, sharp slow-motion catch, immediate viral retention.",
    durationSeconds: 3,
    videoPath: "hooks/ninja-reaction/gxgen_product_dodge.mp4",
    posterPath: "hooks/ninja-reaction/gxgen_product_dodge_poster.jpg"
  }
];

export const GXGEN_NEW_FORMATS = [
  {
    id: "gxgen-format-01-problem-solution",
    categorySlug: "ecommerce-conversion",
    categoryName: "Ecommerce Conversion",
    categoryNameZh: "电商高转化",
    title: "Problem-to-Solution Framework",
    titleZh: "痛点到解决方案框架",
    description: "Open with relatable frustration, amplify consequence, introduce product solution with direct proof.",
    prompt: "Structure:\n1. Hook (0-3s): Present vivid user pain point ('你是不是也遇到过...') with relatable real-world frustration.\n2. Amplify (3-7s): Show the negative consequence of traditional methods or inaction.\n3. Solution (7-12s): Introduce hero product mechanism and core selling point in action.\n4. Proof (12-16s): Demonstrate unmistakable visual evidence and immediate tangible payoff.\n5. CTA (16-20s): Clear, low-friction call-to-action driving instant click/purchase.",
    durationSeconds: 20,
    videoPath: "formats/ecommerce-conversion/gxgen_problem_solution.mp4",
    posterPath: "formats/ecommerce-conversion/gxgen_problem_solution_poster.jpg"
  },
  {
    id: "gxgen-format-02-ugc-testimonial",
    categorySlug: "ecommerce-conversion",
    categoryName: "Ecommerce Conversion",
    categoryNameZh: "电商高转化",
    title: "Authentic UGC Testimonial",
    titleZh: "真实UGC体验证言",
    description: "Peer-to-peer authentic review emphasizing 'why I kept this product' without corporate marketing jargon.",
    prompt: "Structure:\n1. Unfiltered Opener (0-3s): Casual friend-to-friend greeting ('这个我是真的用了才想来讲').\n2. Real Use Context (3-8s): Routine unboxing or daily application showing honest usage texture.\n3. Turning Point (8-14s): The exact moment the user noticed the difference or surprise benefit.\n4. Minor Caveat & True Value (14-18s): Mentioning a minor realistic nuance builds unbeatable trust.\n5. Final Recommendation (18-20s): Direct, friendly encouragement to try it out.",
    durationSeconds: 20,
    videoPath: "formats/ecommerce-conversion/gxgen_ugc_testimonial.mp4",
    posterPath: "formats/ecommerce-conversion/gxgen_ugc_testimonial_poster.jpg"
  },
  {
    id: "gxgen-format-03-comparison-decision",
    categorySlug: "ecommerce-conversion",
    categoryName: "Ecommerce Conversion",
    categoryNameZh: "电商高转化",
    title: "Comparison & Decision Framework",
    titleZh: "竞品与版本对比决策",
    description: "Structured side-by-side comparison helping buyers make rapid, confident purchase decisions.",
    prompt: "Structure:\n1. Confusion Hook (0-3s): Highlight common buyer dilemma ('这两款到底有什么差别，先别急着买').\n2. Side-by-Side Test (3-9s): Direct performance comparison across texture, speed, and durability.\n3. Feature Nuance (9-14s): Detailed macro visual showing where the hero product excels.\n4. Target Recommendation (14-18s): Clear guidance on who should buy which model.\n5. Closing Summary (18-20s): Direct CTA to check current availability.",
    durationSeconds: 20,
    videoPath: "formats/ecommerce-conversion/gxgen_comparison.mp4",
    posterPath: "formats/ecommerce-conversion/gxgen_comparison_poster.jpg"
  },
  {
    id: "gxgen-format-04-recreation-strategy",
    categorySlug: "viral-replication",
    categoryName: "Viral Replication",
    categoryNameZh: "爆款复刻",
    title: "Viral Ad Strategic Replication",
    titleZh: "爆款广告战略级复刻",
    description: "Extract the psychological engine and pacing of proven viral ads into original product concepts.",
    prompt: "Structure:\n1. Scroll-Stopping Beat (0-2s): Recreate the pacing and visual disruption of the benchmark reference.\n2. Strategic Angle Transfer (2-8s): Translate the emotional catalyst into the new product category.\n3. Product Proof Sequence (8-14s): Match the demonstration cadence of the viral hit.\n4. Native Social Cadence (14-18s): Mirror conversational rhythm and text placement.\n5. High-Converting CTA (18-20s): High-intent action trigger.",
    durationSeconds: 20,
    videoPath: "formats/viral-replication/gxgen_recreation_strategy.mp4",
    posterPath: "formats/viral-replication/gxgen_recreation_strategy_poster.jpg"
  },
  {
    id: "gxgen-format-05-shortform-demo",
    categorySlug: "trending-ads",
    categoryName: "Trending Ads",
    categoryNameZh: "热门广告",
    title: "15s Short-Form Product Demo",
    titleZh: "15秒快节奏商品演示",
    description: "High-tempo 15-second product demonstration engineered for maximum TikTok retention.",
    prompt: "Structure:\n1. High-Impact Hook (0-2s): Dynamic macro product movement directly catching the eye.\n2. Benefit In Action (2-8s): Rapid 3-shot montage of hands-on product use in daily situations.\n3. Core Differentiator (8-12s): Macro close-up on unique texture, mechanism, or packaging.\n4. Rapid CTA (12-15s): Floating banner with urgent discount/link guidance.",
    durationSeconds: 15,
    videoPath: "formats/trending-ads/gxgen_shortform_demo.mp4",
    posterPath: "formats/trending-ads/gxgen_shortform_demo_poster.jpg"
  },
  {
    id: "gxgen-format-06-ugc-unboxing",
    categorySlug: "ugc-ads",
    categoryName: "UGC Ads",
    categoryNameZh: "UGC 广告",
    title: "UGC Immersive Unboxing",
    titleZh: "高品质沉浸开箱",
    description: "Tactile, ASMR-infused unboxing experience highlighting premium materials and unboxing joy.",
    prompt: "Structure:\n1. Box Peel Hook (0-3s): Close-up of package seal breaking with satisfying crisp audio.\n2. Reveal & Presentation (3-8s): Unveiling the product from custom protective foam/box.\n3. First Touch & Scent/Texture (8-14s): Creator's spontaneous reaction to touch, weight, and finish.\n4. First Try-Out (14-18s): Instant on-camera first usage.\n5. Value Wrap-up (18-20s): Stating unboxing satisfaction and CTA.",
    durationSeconds: 20,
    videoPath: "formats/ugc-ads/gxgen_ugc_unboxing.mp4",
    posterPath: "formats/ugc-ads/gxgen_ugc_unboxing_poster.jpg"
  },
  {
    id: "gxgen-format-07-tutorial-how-to",
    categorySlug: "product-demos",
    categoryName: "Product Demos",
    categoryNameZh: "产品演示",
    title: "Step-by-Step Tutorial",
    titleZh: "步骤化实操教程",
    description: "Clear, authoritative 3-step practical routine showcasing how to achieve best results.",
    prompt: "Structure:\n1. Desired Outcome Hook (0-3s): Showing the end result first ('想要这种效果，看这3步').\n2. Step 1 Foundation (3-8s): Proper preparation and initial application.\n3. Step 2 Application (8-13s): Hero product technique and key tips for flawless results.\n4. Step 3 Set & Finish (13-17s): Final touch-up demonstrating long-lasting durability.\n5. Action Prompt (17-20s): Save and share CTA.",
    durationSeconds: 20,
    videoPath: "formats/product-demos/gxgen_tutorial.mp4",
    posterPath: "formats/product-demos/gxgen_tutorial_poster.jpg"
  },
  {
    id: "gxgen-format-08-tv-commercial-spot",
    categorySlug: "visual-effects",
    categoryName: "Visual Effects",
    categoryNameZh: "视觉效果",
    title: "TV Commercial Spot",
    titleZh: "广播级商业TVC",
    description: "Cinematic, cinematic commercial storytelling amplifying brand value and emotional resonance.",
    prompt: "Structure:\n1. Cinematic World-Building (0-4s): Wide architectural framing establishing mood and sophistication.\n2. Protagonist Rhythm (4-10s): Dynamic tracking shot following character in peak flow state.\n3. Product Transcendence (10-18s): Fluid transition merging lifestyle with product precision.\n4. Emotional Climax & Identity (18-26s): Highlighting aspirational core brand philosophy.\n5. Iconic Brand Lockup (26-30s): Clean typography and resonant sonic logo.",
    durationSeconds: 30,
    videoPath: "formats/visual-effects/gxgen_tv_spot.mp4",
    posterPath: "formats/visual-effects/gxgen_tv_spot_poster.jpg"
  }
];

export const GXGEN_NEW_STYLES = [
  {
    id: "gxgen-style-01-skyscraper-roofing",
    categorySlug: "urban-epic",
    categoryName: "Urban Epic",
    categoryNameZh: "都市史诗",
    title: "Skyscraper Rooftop Edge",
    titleZh: "摩天大楼天台俯瞰",
    description: "Person on edge of skyscraper rooftop, city skyline stretched out, golden hour wind and scale.",
    prompt: "Atmosphere: Edge of a modern skyscraper rooftop with endless city skyline panoramic backdrop.\nLighting: Warm sunset golden hour with specular rim light hitting hair and product surfaces.\nCamera: Wide selfie angle and slow cinematic drone pull-back showcasing vertigo-inducing urban scale.\nTexture: High-altitude wind flutter, razor-sharp building reflections, fearless effortless luxury.",
    videoPath: "visual-styles/urban-epic/gxgen_roofing.mp4",
    posterPath: "visual-styles/urban-epic/gxgen_roofing_poster.jpg"
  },
  {
    id: "gxgen-style-02-airplane-wing",
    categorySlug: "surreal-extreme",
    categoryName: "Surreal Extreme",
    categoryNameZh: "超现实极限",
    title: "Airplane Wing High Altitude",
    titleZh: "飞行机翼高空测评",
    description: "Person sits on airplane wing mid-flight at altitude, casual review amidst clouds and wind.",
    prompt: "Atmosphere: Sitting casually on the gleaming wing of an airliner cruising above the clouds at 30,000 feet.\nLighting: Blinding crisp high-altitude daylight, vivid sky blue and cloud reflections.\nCamera: Handheld selfie framing with engine turbine blur and rushing cloudscape below.\nTexture: Extreme wind texture, surreal freedom, unforgettable high-retention spectacle.",
    videoPath: "visual-styles/surreal-extreme/gxgen_airplane_wing.mp4",
    posterPath: "visual-styles/surreal-extreme/gxgen_airplane_wing_poster.jpg"
  },
  {
    id: "gxgen-style-03-volcano-rim",
    categorySlug: "surreal-extreme",
    categoryName: "Surreal Extreme",
    categoryNameZh: "超现实极限",
    title: "Active Volcano Rim",
    titleZh: "火山熔岩极限测评",
    description: "Person sits on active volcano rim with bubbling lava below, calm casual product spotlight.",
    prompt: "Atmosphere: Edge of an active volcanic crater with glowing orange lava rivers bubbling below.\nLighting: Dramatic fiery underlighting casting warm ambient orange glows on subject and product.\nCamera: Cinematic handheld framing with rising heat distortion waves and drifting dark ash particles.\nTexture: Magma glow, volcanic stone ruggedness, extreme resilience aura.",
    videoPath: "visual-styles/surreal-extreme/gxgen_volcano.mp4",
    posterPath: "visual-styles/surreal-extreme/gxgen_volcano_poster.jpg"
  },
  {
    id: "gxgen-style-04-bedroom-cozy",
    categorySlug: "natural-living",
    categoryName: "Natural Living",
    categoryNameZh: "自然生活",
    title: "Cozy Bedroom Window Light",
    titleZh: "卧室自然光生活温感",
    description: "Propped against pillows in soft morning light, relaxed wind-down vibe with honest low-effort feel.",
    prompt: "Atmosphere: Unmade duvet, linen pillows, cozy minimalist bedroom interior.\nLighting: Soft diffused morning daylight streaming through sheer white curtains.\nCamera: Casual handheld front camera framing, intimate 35mm eye-level perspective.\nTexture: Warm breathable linen, honest non-commercial authenticity, comforting peer recommendation.",
    videoPath: "visual-styles/natural-living/gxgen_bedroom.mp4",
    posterPath: "visual-styles/natural-living/gxgen_bedroom_poster.jpg"
  },
  {
    id: "gxgen-style-05-nature-trail",
    categorySlug: "natural-living",
    categoryName: "Natural Living",
    categoryNameZh: "自然生活",
    title: "Nature Trail Open Sky",
    titleZh: "户外自然旷野光影",
    description: "Outdoors trail, greenery or beach with natural open sky daylight, clean active mood.",
    prompt: "Atmosphere: Scenic mountain trail, sunlit forest path, or coastal dune breeze.\nLighting: Dynamic dappled sunlight through tree leaves, high clarity open sky illumination.\nCamera: Smooth walking gimbal tracker, fresh environmental depth of field.\nTexture: Pine needles, clean breeze, vibrant earthy greens, healthy outdoor vitality.",
    videoPath: "visual-styles/natural-living/gxgen_nature.mp4",
    posterPath: "visual-styles/natural-living/gxgen_nature_poster.jpg"
  },
  {
    id: "gxgen-style-06-athletic-gym",
    categorySlug: "athletic-performance",
    categoryName: "Athletic Performance",
    categoryNameZh: "高能运动",
    title: "Athletic Gym High Energy",
    titleZh: "健身房高燃运动爆发",
    description: "Gym floor with overhead industrial lighting, post-workout energy highlighting performance and recovery.",
    prompt: "Atmosphere: Modern functional gym or locker room, matte black steel and weight racks.\nLighting: High-contrast directional overhead LEDs casting defined muscle shadows and specular highlights.\nCamera: Low-angle dynamic tracker with subtle motion blur during high-tempo movement.\nTexture: Sweaty glow, chalk dust, industrial metal, peak athletic focus.",
    videoPath: "visual-styles/athletic-performance/gxgen_gym.mp4",
    posterPath: "visual-styles/athletic-performance/gxgen_gym_poster.jpg"
  },
  {
    id: "gxgen-style-07-bathroom-skincare",
    categorySlug: "natural-living",
    categoryName: "Natural Living",
    categoryNameZh: "自然生活",
    title: "Morning Bathroom Vanity",
    titleZh: "晨间浴室清透护肤台",
    description: "Bright bathroom counter, mirror reflection, running water droplets and dewy morning glow.",
    prompt: "Atmosphere: Clean terrazzo or white marble bathroom counter, steaming water droplets on mirror.\nLighting: Bright neutral front vanity lighting, soft shadows for skin perfection.\nCamera: Macro mirror reflection close-up focusing on serum/dropper/texture application.\nTexture: Running water ripples, transparent glass bottle, ultra-clean dewy skin freshness.",
    videoPath: "visual-styles/natural-living/gxgen_bathroom.mp4",
    posterPath: "visual-styles/natural-living/gxgen_bathroom_poster.jpg"
  },
  {
    id: "gxgen-style-08-subway-transit",
    categorySlug: "urban-epic",
    categoryName: "Urban Epic",
    categoryNameZh: "都市史诗",
    title: "Urban Subway Transit",
    titleZh: "都市地铁通勤流动",
    description: "Modern subway train or platform, neon ambient light strips, sleek daily commuter lifestyle.",
    prompt: "Atmosphere: Sleek metro interior or moving train window with streaking neon tunnel lights.\nLighting: Cool ambient carriage lighting with rhythmic flashes of warm station lights.\nCamera: Handheld passenger POV, casual seated or standing hold, cinematic 16:9 vertical center.\nTexture: Stainless steel handrails, headphone lifestyle, fast-paced commuter utility.",
    videoPath: "visual-styles/urban-epic/gxgen_subway.mp4",
    posterPath: "visual-styles/urban-epic/gxgen_subway_poster.jpg"
  },
  {
    id: "gxgen-style-09-modern-office",
    categorySlug: "premium-aesthetics",
    categoryName: "Premium Aesthetics",
    categoryNameZh: "高级美学",
    title: "Modern Open Office Focus",
    titleZh: "现代开放式高压工位",
    description: "Desk, laptop, modern open office setup focusing on productivity, mental energy and elegance.",
    prompt: "Atmosphere: Contemporary open-plan tech office, minimalist walnut desk, monitor glow.\nLighting: Clean balanced ambient architectural lighting with soft window daylight.\nCamera: Ergonomic desktop angle with clean depth of field separating user from background colleagues.\nTexture: Matte anodized aluminum, mechanical keys, coffee steam, sharp productivity.",
    videoPath: "visual-styles/premium-aesthetics/gxgen_office.mp4",
    posterPath: "visual-styles/premium-aesthetics/gxgen_office_poster.jpg"
  },
  {
    id: "gxgen-style-10-culinary-kitchen",
    categorySlug: "natural-living",
    categoryName: "Natural Living",
    categoryNameZh: "自然生活",
    title: "Culinary Kitchen Island",
    titleZh: "料理厨房烟火质感",
    description: "Granite kitchen island, fresh ingredients, warm culinary textures with genuine appetite appeal.",
    prompt: "Atmosphere: Spacious modern home kitchen with butcher block counter and hanging copper cookware.\nLighting: Warm pendant lights combined with crisp countertop task lighting.\nCamera: Top-down 45-degree cooking prep angle and macro pan across fresh sliced ingredients.\nTexture: Sizzling steam, fresh herbs, wooden grain, rich culinary sensory delight.",
    videoPath: "visual-styles/natural-living/gxgen_kitchen.mp4",
    posterPath: "visual-styles/natural-living/gxgen_kitchen_poster.jpg"
  },
  {
    id: "gxgen-style-11-hyper-motion",
    categorySlug: "premium-aesthetics",
    categoryName: "Premium Aesthetics",
    categoryNameZh: "高级美学",
    title: "Hyper Motion Commercial",
    titleZh: "商业高动态视觉",
    description: "High-speed camera transitions, dynamic kinetic lighting, and intense commercial focus.",
    prompt: "Atmosphere: High-tech studio stage with kinetic robotic camera movement.\nLighting: Dynamic moving key lights, high-speed strobes freezing micro-movement.\nCamera: 360-degree orbital whip pans, instantaneous speed ramps between 120fps and 24fps.\nTexture: Carbon fiber, polished chrome, zero latency kinetic energy, flagship grade.",
    videoPath: "visual-styles/premium-aesthetics/gxgen_hyper_motion.mp4",
    posterPath: "visual-styles/premium-aesthetics/gxgen_hyper_motion_poster.jpg"
  },
  {
    id: "gxgen-style-12-authentic-social",
    categorySlug: "youth-trends",
    categoryName: "Youth Trends",
    categoryNameZh: "青年潮流",
    title: "Authentic Social Raw",
    titleZh: "原生社媒真实质感",
    description: "Zero filter, front-facing mobile smartphone lens aesthetic, believable and conversational.",
    prompt: "Atmosphere: Everyday apartment hallway or bathroom with spontaneous lighting.\nLighting: Unfiltered natural phone camera exposure, authentic slight grain, true colors.\nCamera: True vertical smartphone selfie angle with natural micro-sway and close distance.\nTexture: Authentic relatable social vibe, maximum trust factor, viral friend-group sharing.",
    videoPath: "visual-styles/youth-trends/gxgen_social_raw.mp4",
    posterPath: "visual-styles/youth-trends/gxgen_social_raw_poster.jpg"
  },
  {
    id: "gxgen-style-13-golden-hour-urban",
    categorySlug: "natural-living",
    categoryName: "Natural Living",
    categoryNameZh: "自然生活",
    title: "Urban Golden Hour Film",
    titleZh: "城市日落暮色胶片",
    description: "Subtle vintage 35mm film grain during downtown golden hour, warm nostalgia and romantic depth.",
    prompt: "Atmosphere: Metropolitan street crossing or outdoor terrace at dusk.\nLighting: Warm amber sunburst backlight, long shadows and soft romantic flare.\nCamera: Cinematic 50mm portrait lens, gentle handheld sway, dreamy optical vignetting.\nTexture: Authentic Kodak Portra 400 grain, warm cinematic glow, nostalgic brand romance.",
    videoPath: "visual-styles/natural-living/gxgen_golden_hour.mp4",
    posterPath: "visual-styles/natural-living/gxgen_golden_hour_poster.jpg"
  },
  {
    id: "gxgen-style-14-minimal-studio-macro",
    categorySlug: "future-technology",
    categoryName: "Future Technology",
    categoryNameZh: "未来科技",
    title: "Minimal Studio Macro",
    titleZh: "极简棚拍微距精修",
    description: "Flawless studio tabletop with shadowless softboxes, revealing ultra-fine product textures.",
    prompt: "Atmosphere: Clean monolithic pedestal inside a matte studio infinity cove.\nLighting: Triple diffused softboxes providing surgical, gradient-free edge highlights.\nCamera: 100mm macro probe lens gliding 2mm above the product surface.\nTexture: Matte anodized metal, micro-embossed logos, surgical cleanliness, elite craftsmanship.",
    videoPath: "visual-styles/future-technology/gxgen_studio_macro.mp4",
    posterPath: "visual-styles/future-technology/gxgen_studio_macro_poster.jpg"
  }
];
