import test from 'node:test'
import assert from 'node:assert/strict'
import { runVerified, requireConfig } from './sidebar-run.mjs'
import { observeMotion } from './sidebar-fullscreen-motion.ego.mjs'
test('motion capture failure preserves click failure',async()=>{let n=0;const page={evaluate:async()=>{if(n++)throw Error('capture failed')},click:async()=>{throw Error('click failed')}};await assert.rejects(()=>observeMotion(page,['Fullscreen'],async()=>{}),e=>e.message==='click failed'&&e.secondaryErrors?.[0]==='capture failed')})
for(const value of [null,undefined,''])for(const stage of ['execute','capture','cleanup'])test('non Error throw '+stage+' '+String(value),async()=>{let cleaned=false;const r=await runVerified({required:['a'],execute:async mark=>{mark('a');if(stage==='execute')throw value;if(stage==='capture')throw Error('primary')},capture:async()=>{if(stage==='capture')throw value},cleanup:async()=>{cleaned=true;if(stage==='cleanup')throw value}});assert.equal(r.passed,false);assert.ok(cleaned);if(stage==='execute')assert.equal(r.error,String(value));if(stage==='capture')assert.equal(r.error,'primary')})
test('explicit configuration required',()=>{assert.throws(()=>requireConfig({}),/EGO_TASK_ID/);assert.throws(()=>requireConfig({EGO_TASK_ID:'740'}),/EVIDENCE_DIR/)})
test('missing required case fails',async()=>{const r=await runVerified({required:['a','b'],execute:async mark=>mark('a'),capture:async()=>{},cleanup:async()=>{}});assert.equal(r.passed,false);assert.deepEqual(r.missing,['b'])})
test('capture precedes cleanup and secondary errors retain primary',async()=>{const order=[];const r=await runVerified({required:['a'],execute:async()=>{throw Error('prepare')},capture:async()=>{order.push('capture');throw Error('capture')},cleanup:async()=>{order.push('cleanup');throw Error('cleanup')}});assert.deepEqual(order,['capture','cleanup']);assert.equal(r.error,'prepare');assert.equal(r.passed,false);assert.equal(r.secondaryErrors.length,2)})
test('only full completion with successful cleanup passes',async()=>{for(const fail of [false,true]){const r=await runVerified({required:['a'],execute:async mark=>mark('a'),capture:async()=>{},cleanup:async()=>{if(fail)throw Error('release')}});assert.equal(r.passed,!fail)}})
