import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, renameSync, symlinkSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { once } from 'node:events'
import { finished } from 'node:stream/promises'
import { createHash } from 'node:crypto'
import { SafeStorageFS } from './storage-fs.js'
import { AssetsRuntime } from './storage-runtime.js'

async function fixture(t) {
  const dir = mkdtempSync(fileURLToPath(new URL('./.storage-stream-', import.meta.url)))
  const root = join(dir, 'root')
  mkdirSync(root)
  const fs = new SafeStorageFS()
  await fs.probe()
  t.after(async () => {
    const child = fs.child
    const exited = child && child.exitCode === null && child.signalCode === null ? once(child, 'exit') : Promise.resolve()
    fs.dispose()
    await exited
    rmSync(dir, { recursive: true, force: true })
  })
  return { dir, root, fs, expectedRoot: await fs.identity(root) }
}

async function digest(readable) {
  const hash = createHash('sha256')
  let size = 0
  for await (const chunk of readable) { hash.update(chunk); size += chunk.length }
  return { sha256: hash.digest('hex'), size }
}

function track(fs) {
  const request = fs.request.bind(fs)
  const state = { reads: 0, closes: 0, key: null }
  fs.request = async (op, ...args) => {
    if (op === 'stream_read') state.reads++
    if (op === 'stream_close') state.closes++
    const result = await request(op, ...args)
    if (op === 'stream_open') state.key = result.key
    return result
  }
  return state
}

for (const size of [0, 257, 2 * 1024 * 1024 + 17]) {
  test(`real FD stream yields exact generated bytes (${size}) and releases on EOF`, async (t) => {
    const { root, fs, expectedRoot } = await fixture(t)
    const sample = Buffer.alloc(size, 0xa7)
    writeFileSync(join(root, 'sample'), sample)
    const state = track(fs)
    const opened = await fs.openReadStream(root, 'sample', { expectedRoot })
    assert.equal(opened.size, size)
    assert.equal(opened.identity.ino, String(statSync(join(root, 'sample')).ino))
    assert.equal(opened.identity.size, String(size))
    assert.deepEqual(await digest(opened.readable), { size, sha256: createHash('sha256').update(sample).digest('hex') })
    await Promise.all([opened.close(), opened.close()])
    assert.equal(state.closes, 1)
    await assert.rejects(fs.request('stream_read', { key: state.key }), { code: 'recovery-required' })
  })
}

test('stream stays on the opened FD after root and parent paths are replaced', async (t) => {
  const { dir, root, fs, expectedRoot } = await fixture(t)
  mkdirSync(join(root, 'parent'))
  writeFileSync(join(root, 'parent/file'), 'original-fd')
  const opened = await fs.openReadStream(root, 'parent/file', { expectedRoot })
  renameSync(root, join(dir, 'retained'))
  mkdirSync(root)
  mkdirSync(join(root, 'parent'))
  writeFileSync(join(root, 'parent/file'), 'replacement')
  assert.deepEqual(await digest(opened.readable), { size: 11, sha256: createHash('sha256').update('original-fd').digest('hex') })
  await opened.close()
  await assert.rejects(fs.openReadStream(root, 'parent/file', { expectedRoot }), { code: 'root-identity-changed' })
})

test('backpressure pulls at most one queued chunk and early cancellation closes helper FD once', async (t) => {
  const { root, fs, expectedRoot } = await fixture(t)
  writeFileSync(join(root, 'sample'), Buffer.alloc(4 * 1024 * 1024, 1))
  const state = track(fs)
  const opened = await fs.openReadStream(root, 'sample', { expectedRoot })
  assert.equal(state.reads, 0)
  const ready = once(opened.readable, 'readable')
  opened.readable.read(0)
  await ready
  // A worker round trip gives queued pulls a chance to occur without a timer.
  await fs.identity(root)
  assert.equal(state.reads, 1)
  assert.ok(opened.readable.readableLength <= 64 * 1024)
  await Promise.all([opened.close(), opened.close()])
  assert.equal(state.closes, 1)
  assert.equal(opened.readable.destroyed, true)
  await assert.rejects(fs.request('stream_read', { key: state.key }), { code: 'recovery-required' })
})

test('cancellation before reading and during an outstanding pull is idempotent', async (t) => {
  const { root, fs } = await fixture(t)
  writeFileSync(join(root, 'sample'), Buffer.alloc(256 * 1024, 2))
  for (const pull of [false, true]) {
    const state = track(fs)
    const opened = await fs.openReadStream(root, 'sample', {})
    if (pull) opened.readable.read(0)
    await Promise.all([opened.close(), opened.close()])
    await assert.rejects(fs.request('stream_read', { key: state.key }), { code: 'recovery-required' })
  }
})

test('root, ancestor, internal-parent and leaf symlink escapes and unsafe paths are denied', async (t) => {
  const { dir, root, fs, expectedRoot } = await fixture(t)
  const outside = join(dir, 'outside')
  mkdirSync(outside)
  writeFileSync(join(outside, 'sentinel'), 'outside')
  symlinkSync(outside, join(root, 'parent'))
  symlinkSync(join(outside, 'sentinel'), join(root, 'leaf'))
  symlinkSync(root, join(dir, 'root-link'))
  symlinkSync(dir, join(dir, 'ancestor-link'))
  for (const [base, rel] of [[root, 'parent/sentinel'], [root, 'leaf'], [root, '../outside/sentinel'], [root, '/sentinel'], [root, 'bad\\path'], [join(dir, 'root-link'), 'leaf'], [join(dir, 'ancestor-link/root'), 'leaf']]) {
    await assert.rejects(fs.openReadStream(base, rel, { expectedRoot }), { code: 'path-denied' })
  }
  assert.equal(statSync(join(outside, 'sentinel')).size, 7)
})

test('expectedRoot mismatches fail before resolve; directory and missing file do not become streams', async (t) => {
  const { root, fs, expectedRoot } = await fixture(t)
  writeFileSync(join(root, 'sample'), 'bytes')
  for (const key of ['path', 'dev', 'ino', 'fsid']) {
    await assert.rejects(fs.openReadStream(root, 'sample', { expectedRoot: { ...expectedRoot, [key]: 'mismatch' } }), { code: 'root-identity-changed' })
  }
  await assert.rejects(fs.openReadStream(root, 'sample', { expectedRoot: {} }), { code: 'root-identity-changed' })
  mkdirSync(join(root, 'directory'))
  await assert.rejects(fs.openReadStream(root, 'directory', { expectedRoot }), { code: 'path-denied' })
  await assert.rejects(fs.openReadStream(root, 'missing', { expectedRoot }), { code: 'storage-offline' })
})

test('file mutation errors terminate the stream and release the FD', async (t) => {
  const { root, fs, expectedRoot } = await fixture(t)
  writeFileSync(join(root, 'sample'), 'before')
  const state = track(fs)
  const opened = await fs.openReadStream(root, 'sample', { expectedRoot })
  writeFileSync(join(root, 'sample'), 'changed-by-external-writer')
  await assert.rejects(digest(opened.readable), { code: 'plan-stale' })
  await opened.close()
  await assert.rejects(fs.request('stream_read', { key: state.key }), { code: 'recovery-required' })
})

for (const mode of ['SIGKILL', 'stdin-eof', 'dispose']) {
  test(`paused stream terminates and releases after worker ${mode}`, async (t) => {
    const { root, fs, expectedRoot } = await fixture(t)
    writeFileSync(join(root, 'sample'), Buffer.alloc(256 * 1024, 3))
    const opened = await fs.openReadStream(root, 'sample', { expectedRoot })
    const child = fs.child
    const exit = once(child, 'exit')
    const terminal = finished(opened.readable).then(() => null, (error) => error)
    if (mode === 'SIGKILL') child.kill('SIGKILL')
    else if (mode === 'stdin-eof') child.stdin.end()
    else fs.dispose()
    await exit
    const error = await terminal
    assert.ok(error)
    assert.equal(opened.readable.destroyed, true)
    await opened.close()
    assert.equal(fs.streams.size, 0)
  })
}

test('real helper preview keeps runtime commit lease until FD close completes', async (t) => {
  const { dir } = await fixture(t)
  const runtime = new AssetsRuntime(join(dir, 'home'))
  await runtime.initialize()
  t.after(async () => {
    const child = runtime.fs.child
    const exited = child && child.exitCode === null && child.signalCode === null ? once(child, 'exit') : Promise.resolve()
    runtime.dispose()
    await exited
  })
  writeFileSync(join(runtime.config.active.path, 'sample'), Buffer.alloc(256 * 1024, 7))
  const state = track(runtime.fs)
  const preview = await runtime.preview(() => ({ relativePath: 'sample' }))
  assert.equal(runtime.readers, 1)
  let committed = false
  const commit = runtime.beginCommit().then(() => { committed = true })
  await runtime.fs.identity(runtime.config.active.path)
  assert.equal(committed, false)
  await assert.rejects(runtime.preview(() => ({ relativePath: 'sample' })), { code: 'storage-busy' })
  await Promise.all([preview.release(), preview.release()])
  await commit
  assert.equal(runtime.readers, 0)
  assert.equal(state.closes, 1)
  await assert.rejects(runtime.fs.request('stream_read', { key: state.key }), { code: 'recovery-required' })
})

test('missing Python helper rejects open with explicit unsupported error', async () => {
  const fs = new SafeStorageFS('/nonexistent-storage-python')
  await assert.rejects(fs.openReadStream('/unused', 'sample', {}), { code: 'storage-platform-unsupported' })
  fs.dispose()
})
