/** Topview AI Marketer quick actions & popular starters, captured 2026-09-09. */
export const STARTER_GROUPS = ['market-insights', 'listing-reviews', 'content-creators', 'ad-analytics']
export const STARTERS = [
  { id: 'category-opportunity', group: 'market-insights', icon: 'chart-column' },
  { id: 'trending-products', group: 'market-insights', icon: 'chart-column' },
  { id: 'competitor-scan', group: 'market-insights', icon: 'chart-column' },
  { id: 'title-optimization', group: 'listing-reviews', icon: 'file-pen' },
  { id: 'review-insights', group: 'listing-reviews', icon: 'message-square-text' },
  { id: 'ugc-brief', group: 'content-creators', icon: 'clapperboard' },
  { id: 'video-scripts', group: 'content-creators', icon: 'clapperboard' },
  { id: 'recreate-viral-ads', group: 'content-creators', icon: 'wand-sparkles' },
  { id: 'search-terms', group: 'ad-analytics', icon: 'chart-column' },
  { id: 'roas-analysis', group: 'ad-analytics', icon: 'chart-line' },
]

/** 热门入门方式 (4个大卡片) */
export const POPULAR_STARTERS = [
  {
    id: 'marketing-insight',
    type: 'modal',
  },
  {
    id: 'url-to-video',
    type: 'modal', // 视频网址全功能弹窗已激活落地
  },
  {
    id: 'recreate-viral-ads',
    type: 'modal', // 复刻爆款视频（重现病毒式广告）全功能模态框已激活落地
  },
  {
    id: 'bulk-create-ads',
    type: 'modal', // 批量创建广告（Bulk Create Ads）全功能模态框已激活落地
  },
]

/** 营销洞察模态框内的 6 项推荐定义 */
export const MARKETING_INSIGHT_ITEMS = [
  {
    id: 'tiktok-creators',
    icon: 'clapperboard',
    prompt: 'Find and shortlist TikTok creators for [product/brand] in [target market]. Evaluate audience fit, content style, engagement quality, brand safety, and collaboration potential, then recommend campaign roles and outreach angles.',
  },
  {
    id: 'ads-roas',
    icon: 'chart-line',
    prompt: '[file://ads report]\n\nAnalyze performance on [platform] for [date range] against [target ROAS/CPA], considering [attribution window] and [product://product margin]. Evaluate campaign, ad group or ad set, and ad-level spend, revenue, ROAS, CPA, CTR, CPC, and conversion rate; identify budget, audience, bidding, creative, and landing-page issues; and prioritize what to pause, scale, or test next. Distinguish data-backed findings from assumptions. If context is missing, ask an open follow-up question about useful report information.',
  },
  {
    id: 'amazon-a-plus',
    icon: 'file-pen',
    prompt: 'Create an Amazon A+ Content brief for [product://target product], including the content structure, key messages, module recommendations, and visual direction.',
  },
  {
    id: 'amazon-search-terms',
    icon: 'chart-column',
    prompt: 'Analyze [file://search term report] from [platform] for [date range], using [attribution settings] and [target metrics]. Identify high-performing queries, wasted ad spend, negative-keyword opportunities, and bid or budget actions. Separate data-backed findings from assumptions. If context is missing, ask an open follow-up question about useful report information.',
  },
  {
    id: 'category-market',
    icon: 'chart-column',
    prompt: 'Analyze the potential of [product category] on [ecommerce platform] in [target market]. Evaluate demand, competition, pricing, customer needs, barriers to entry, and growth signals; clearly distinguish facts, inferences, and assumptions; and recommend whether and how to enter. If context is missing, ask an open follow-up question about any useful reference information.',
  },
  {
    id: 'title-optimization',
    icon: 'file-pen',
    prompt: 'Optimize [current product title] for [ecommerce platform] using [product://product details]. Improve search visibility, keyword relevance, readability, differentiation, and conversion while following the platform’s requirements. Provide the recommended title with a concise rationale. If context is missing, ask an open follow-up question about useful product information.',
  },
]

/** 视频网址（URL to Video）视觉风格选项 */
export const URL_TO_VIDEO_STYLES = [
  { id: 'clean-studio', label: 'Clean studio', labelZh: '清新影棚' },
  { id: 'cinematic-luxury', label: 'Cinematic luxury', labelZh: '电影感奢华' },
  { id: 'minimalist-premium', label: 'Minimalist premium', labelZh: '极简高级' },
  { id: 'natural-lifestyle', label: 'Natural lifestyle', labelZh: '自然生活' },
  { id: 'bold-colorful', label: 'Bold & colorful', labelZh: '鲜亮大胆' },
  { id: 'futuristic-tech', label: 'Futuristic tech', labelZh: '未来科技' },
  { id: 'ugc-style', label: 'UGC style', labelZh: '真实口播' },
  { id: 'unboxing', label: 'Unboxing', labelZh: '开箱测评' },
  { id: 'street-style', label: 'Street style', labelZh: '街头潮流' },
]

/** 视频网址（URL to Video）画幅比例选项 */
export const URL_TO_VIDEO_RATIOS = [
  { id: '21:9', label: '21:9', width: 30, height: 13 },
  { id: '16:9', label: '16:9', width: 28, height: 16 },
  { id: '4:3', label: '4:3', width: 24, height: 18 },
  { id: '1:1', label: '1:1', width: 20, height: 20 },
  { id: '3:4', label: '3:4', width: 18, height: 24 },
  { id: '9:16', label: '9:16', width: 16, height: 28 },
]

/** 视频网址（URL to Video）示例轮播数据（默认对齐灵感社区真实爆款样本） */
export const URL_TO_VIDEO_EXAMPLES = [
  {
    id: 'unboxing',
    title: '开箱测评：多功能料理机',
    titleEn: 'Kitchen Appliance UGC Demo',
    tag: '示例',
    tagEn: 'EXAMPLE',
    badge: 'UGC',
    desc: '开箱特写、配件展示与实机演示',
    coverUrl: '/omnimux/inspiration/local/media/covers/cover_bb720927.jpeg',
    videoUrl: '/omnimux/inspiration/local/media/videos/video_0437e3fa.mp4',
  },
  {
    id: 'food-snack',
    title: '美食快消：香脆薯条零食',
    titleEn: 'Crispy Fries Snack Commercial',
    tag: '示例',
    tagEn: 'EXAMPLE',
    badge: 'Food',
    desc: '酥脆质感、诱人色泽与情绪反应',
    coverUrl: '/omnimux/inspiration/local/media/covers/cover_987b8524.jpeg',
    videoUrl: '/omnimux/inspiration/local/media/videos/video_a5edfaab.mp4',
  },
  {
    id: 'fashion-model',
    title: '时尚穿搭：法式优雅风衣',
    titleEn: 'Autumn Trench Coat Showcase',
    tag: '示例',
    tagEn: 'EXAMPLE',
    badge: 'Fashion',
    desc: '自然光影、版型剪裁与动态垂坠感',
    coverUrl: '/omnimux/inspiration/local/media/covers/cover_3bc9ec01.jpeg',
    videoUrl: '/omnimux/inspiration/local/media/videos/video_211675ca.mp4',
  },
]

/** 复刻爆款视频（Recreate Viral Ads）示例对比卡片数据 (默认对齐灵感社区真实爆款样本) */
export const RECREATE_VIRAL_ADS_EXAMPLES = [
  {
    id: 'ugc-comparison',
    title: '重现病毒式广告：美妆开箱',
    titleEn: 'Beauty UGC Review Recreation',
    tag: '示例',
    tagEn: 'EXAMPLE',
    originalTitle: '原视频：桌面美妆好物测评',
    recreatedTitle: '复刻生成：新品牌口红礼盒',
    coverLeft: '/omnimux/inspiration/local/media/covers/cover_bb720927.jpeg',
    coverRight: '/omnimux/inspiration/local/media/covers/cover_3bc9ec01.jpeg',
    desc: '重现视频结构，或替换人物和产品，同时保留原始创意。',
    descEn: 'Recreate video structure, or swap people and products while keeping the original idea.',
  },
  {
    id: 'food-commercial',
    title: '重现病毒式广告：香脆薯条',
    titleEn: 'Crispy Snack Commercial Ad',
    tag: '示例',
    tagEn: 'EXAMPLE',
    originalTitle: '原视频：餐厅经典薯条特写',
    recreatedTitle: '复刻生成：坚果零食解馋场景',
    coverLeft: '/omnimux/inspiration/local/media/covers/cover_987b8524.jpeg',
    coverRight: '/omnimux/inspiration/local/media/covers/cover_bb720927.jpeg',
    desc: '保留黄金3秒吸睛镜头与让人垂涎的食欲特写。',
    descEn: 'Preserve the golden 3-second hook and appetizing food close-ups.',
  },
  {
    id: 'street-fashion',
    title: '重现病毒式广告：街头穿搭',
    titleEn: 'Street Style Apparel Showcase',
    tag: '示例',
    tagEn: 'EXAMPLE',
    originalTitle: '原视频：欧美街拍连帽衫',
    recreatedTitle: '复刻生成：新潮撞色运动外套',
    coverLeft: '/omnimux/inspiration/local/media/covers/cover_3bc9ec01.jpeg',
    coverRight: '/omnimux/inspiration/local/media/covers/cover_987b8524.jpeg',
    desc: '卡点变装与动感运镜节奏完整继承，无缝替换服饰产品。',
    descEn: 'Keep the beat-matched transition rhythm and seamlessly replace apparel.',
  },
]

/** 批量创建广告（Bulk Create Ads）画幅比例选项 */
export const BULK_CREATE_RATIOS = [
  { id: '16:9', label: '16:9', width: 28, height: 16 },
  { id: '4:3', label: '4:3', width: 24, height: 18 },
  { id: '1:1', label: '1:1', width: 20, height: 20 },
  { id: '3:4', label: '3:4', width: 18, height: 24 },
  { id: '9:16', label: '9:16', width: 16, height: 28 },
]

/** 批量创建广告（Bulk Create Ads）扇形展开轮播示例卡片 */
export const BULK_CREATE_ADS_EXAMPLES = [
  {
    id: 'headphones',
    title: '智能降噪发光耳机',
    titleEn: 'Smart Glowing Headphones',
    tag: 'EXAMPLE',
    tagZh: '示例',
    coverUrl: '/omnimux/inspiration/local/media/covers/cover_bb720927.jpeg',
  },
  {
    id: 'streetwear',
    title: '街头复古穿搭系列',
    titleEn: 'Vintage Streetwear Collection',
    tag: 'EXAMPLE',
    tagZh: '示例',
    coverUrl: '/omnimux/inspiration/local/media/covers/cover_3bc9ec01.jpeg',
  },
  {
    id: 'snack-drink',
    title: '元气快消饮品特写',
    titleEn: 'Energy Drink Commercial',
    tag: 'EXAMPLE',
    tagZh: '示例',
    coverUrl: '/omnimux/inspiration/local/media/covers/cover_987b8524.jpeg',
  },
]

export const guideZh = {
  "guide.title": "开始一个营销任务",
  "guide.market-insights": "市场洞察",
  "guide.listing-reviews": "列表和评论",
  "guide.content-creators": "内容与创作者",
  "guide.ad-analytics": "广告分析",
  "guide.category-opportunity.title": "品类机会",
  "guide.category-opportunity.prompt": "分析[产品品类]在[目标市场]的[电商平台]上的潜力。评估需求、竞争、定价、客户需求、进入壁垒和增长信号；明确区分事实、推断和假设；并建议是否进入以及如何进入。如果缺少背景信息，请用开放式问题追问有用的参考资料。",
  "guide.trending-products.title": "热门产品",
  "guide.trending-products.prompt": "结合[业务背景或限制条件]，找出[目标市场]的[电商平台]上[品类/产品]中具有较强销售潜力的热门产品。解释每项推荐背后的需求信号、受众匹配度、竞争强度、定价机会、季节性和运营风险。如果缺少背景信息，请用开放式问题追问有用的参考资料。",
  "guide.competitor-scan.title": "竞争对手扫描",
  "guide.competitor-scan.prompt": "分析[目标市场]的[电商平台]上[对标商品/品类]中排名靠前的竞品商品页面。比较定位、定价、优惠、评论、内容、卖点和转化策略，并找出具体的差异化机会。如果缺少背景信息，请用开放式问题追问有用的参考资料。",
  "guide.title-optimization.title": "标题优化",
  "guide.title-optimization.prompt": "根据[product://关联产品详情]，为[电商平台]优化[当前商品标题]。在遵守平台要求的前提下，提升搜索可见度、关键词相关性、可读性、差异化和转化效果。给出推荐标题及简要理由。如果缺少背景信息，请用开放式问题追问有用的产品信息。",
  "guide.review-insights.title": "评论洞察",
  "guide.review-insights.prompt": "使用[file://导出的评论数据]，分析[目标市场]中[product://目标产品]的客户评论。找出反复出现的抱怨、未满足的需求、购买动机、用语模式，以及产品改进或传播表达的机会。尽可能量化各类主题，并区分证据与假设。如果缺少背景信息，请用开放式问题追问有用的参考资料。",
  "guide.ugc-brief.title": "UGC 简报",
  "guide.ugc-brief.prompt": "为[product://主推产品]制定在[目标市场]的[平台]上使用的 UGC 视频简报，面向[目标受众]，结合[assets://参考模特/风格]，在[限制条件]内支持[营销活动目标]。包括核心信息、拍摄指南、必需镜头、交付物和成功标准。如果缺少背景信息，请用开放式问题追问有用的营销活动资料。",
  "guide.video-scripts.title": "视频脚本",
  "guide.video-scripts.prompt": "为[product://主推产品]撰写 10 个用于[平台]的短视频脚本，面向[目标受众]，结合[assets://演员/角色]，体现[优惠方案]和[语气风格]。每个脚本都应包含有力的开头钩子、能引起共鸣的场景、产品演示、支撑卖点的证据和行动号召，并提供足够的创意差异以便测试。如果缺少背景信息，请用开放式问题追问有用的创意资料。",
  "guide.recreate-viral-ads.title": "复制病毒式广告",
  "guide.recreate-viral-ads.prompt": "使用所选的复刻模式和参考素材复刻这条视频。",
  "guide.search-terms.title": "搜索词",
  "guide.search-terms.prompt": "根据[归因设置]和[目标指标]，分析[平台]在[日期范围]内的[file://搜索词报告]。找出表现优秀的搜索词、浪费的广告支出、否定关键词机会，以及出价或预算调整措施。区分有数据支持的发现与假设。如果缺少背景信息，请用开放式问题追问有用的报告资料。",
  "guide.roas-analysis.title": "广告支出回报率分析",
  "guide.roas-analysis.prompt": "[file://广告投放报告]\n\n结合[归因窗口]和[product://关联产品]，按照[目标 ROAS/CPA]分析[平台]在[日期范围]内的表现。评估广告系列、广告组和单条广告层级的支出、收入、广告支出回报率（ROAS）、单次转化成本（CPA）、点击率（CTR）、单次点击成本（CPC）和转化率；找出预算、受众、出价、创意及落地页问题；并按优先级给出接下来应暂停、扩大投放或测试的项目。区分有数据支持的发现与假设。如果缺少背景信息，请用开放式问题追问有用的报告资料。",
  "guide.unavailable": "输入框尚未准备好，请稍后重试。",
  "guide.retry": "重试",

  // 热门入门方式文案
  "guide.popular.title": "热门入门方式",
  "guide.popular.marketing-insight.title": "营销洞察",
  "guide.popular.url-to-video.title": "视频网址",
  "guide.popular.recreate-viral-ads.title": "复刻爆款视频",
  "guide.popular.bulk-create-ads.title": "批量创建广告",
  "guide.popular.creative-presets.title": "批量创建广告",
  "guide.popular.placeholder-notice": "该功能正在接入中，敬请期待！",

  // 营销洞察模态框文案
  "guide.insight.modal.title": "营销洞察",
  "guide.insight.modal.subtitle": "选择您想要探索的内容，并为代理提供足够的背景信息，使其能够将其转化为一项专注的营销任务。",
  "guide.insight.suggested": "为您推荐",
  "guide.insight.explore.title": "您想要探索什么？",
  "guide.insight.start-btn": "开始洞察 →",
  "guide.insight.copied": "已添加到剪贴板",
  "guide.insight.applied": "已填入会话输入框，可直接发送",

  // 6个洞察子项标题
  "guide.insight.tiktok-creators.title": "TikTok创作者与网红研究",
  "guide.insight.ads-roas.title": "广告ROAS分析",
  "guide.insight.amazon-a-plus.title": "亚马逊A+内容简介",
  "guide.insight.amazon-search-terms.title": "亚马逊搜索词报告分析",
  "guide.insight.category-market.title": "品类市场分析",
  "guide.insight.title-optimization.title": "产品列表标题优化",

  // 6个洞察子项预填 Prompt (DSH 中文语言适配)
  "guide.insight.tiktok-creators.prompt": "请为[目标市场]中的[产品/品牌]寻找并筛选候选 TikTok 创作者。\n从以下维度进行专业评估：\n1. 受众画像与受众契合度\n2. 内容风格与视觉调性\n3. 真实互动质量与完播表现\n4. 品牌安全性与舆情合规\n5. 商业转化潜力与合作意向\n最后给出具体的合作营销角色建议与建联触达切入点。如果缺少关键背景信息，请向我追问。",
  "guide.insight.ads-roas.prompt": "[file://广告投放报告]\n\n结合[归因窗口]和[product://关联产品]，按照[目标 ROAS/CPA]对[平台]在[日期范围]内的广告投放表现进行多维度诊断：\n1. 分层评估广告系列、广告组与单条素材层级的消耗、收入、ROAS、CPA、CTR、CPC 与转化率；\n2. 深入定位预算分配、受众圈选、出价策略、素材创意及落地页转化瓶颈；\n3. 给出清晰的操盘优先级建议：哪些应立即暂停止损、哪些应加大预算放量、哪些需要建立新创意测试组。\n请明确区分有数据支撑的客观事实与假设推断。若报告信息不全，请向我追问。",
  "guide.insight.amazon-a-plus.prompt": "请为[product://主推产品]设计一份专业且高转化率的亚马逊 A+ 页面（EBC）内容创作简报，包含：\n1. 整体叙事结构与版块编排逻辑\n2. 核心卖点与差异化价值提炼（Key Messages）\n3. 推荐使用的 A+ 官方模块组合与图文排版\n4. 视觉设计风格、配色体系与拍摄布光建议\n如果缺少产品详情或竞品背景，请向我提出针对性的补充问题。",
  "guide.insight.amazon-search-terms.prompt": "根据[归因设置]和[目标核心指标]，深入分析[平台]在[日期范围]内的[file://搜索词报告]：\n1. 筛选出高点击率、高转化率的高效搜索词（Golden Keywords）；\n2. 识别出高消耗低转化的浪费型搜索词，并提供否定关键词（Negative Keywords）清单；\n3. 给出精准竞价调整策略与广告活动预算优化建议。\n请严格基于真实数据分析，明确区分事实与推断。若关键报表数据缺失，请向我追问。",
  "guide.insight.category-market.prompt": "请全面分析[产品品类]在[目标市场]的[电商/社媒平台]上的商业机会与增长潜力：\n1. 评估市场需求规模、季节性特征与增长信号；\n2. 剖析现有主要竞争对手格局与定价带区间；\n3. 挖掘目标消费者的核心痛点、未满足需求与进入壁垒；\n4. 明确给出是否建议入场以及具体的差异化切入策略。\n请明确区分客观事实、行业推断与假设。如果缺少背景信息，请向我提出开放式问题以获取补充材料。",
  "guide.insight.title-optimization.prompt": "请根据[product://关联产品详情]，为[电商平台]深度优化[当前商品标题]：\n1. 严格遵守平台的字符限制与排版规则（避免违规堆砌）；\n2. 最大化提升核心大词与长尾词的搜索权重与搜索可见度；\n3. 兼顾高可读性、产品差异化与点击转化吸引力；\n4. 提供 3 个不同侧重点（如搜索权重优先型、卖点吸引型、品牌调性型）的推荐标题，并附带简要修改理由。\n如果缺少必要的产品参数，请向我追问。",

  // 视频网址（URL to Video）模态框文案
  "guide.url-to-video.modal.title": "视频网址",
  "guide.url-to-video.modal.subtitle": "将产品页面转化为可直接投放的视频广告。",
  "guide.url-to-video.product-url.label": "产品网址",
  "guide.url-to-video.product-url.placeholder": "输入或粘贴产品页面网址...",
  "guide.url-to-video.target-audience.label": "目标受众",
  "guide.url-to-video.target-audience.placeholder": "这条广告主要面向哪些人群？",
  "guide.url-to-video.key-selling-point.label": "核心卖点",
  "guide.url-to-video.key-selling-point.placeholder": "最希望突出的核心优势是什么？",
  "guide.url-to-video.visual-style.label": "视觉风格",
  "guide.url-to-video.duration.label": "目标时长",
  "guide.url-to-video.duration.auto": "自动",
  "guide.url-to-video.duration.hint": "让模型根据产品内容自动选择适宜时长",
  "guide.url-to-video.aspect-ratio.label": "画幅比例",
  "guide.url-to-video.submit-btn": "开始制作 →",
  "guide.url-to-video.url-required": "请先输入产品页面网址",
  "guide.url-to-video.applied": "已生成视频广告制作任务草稿",

  // 9 种视觉风格字典
  "guide.url-to-video.style.clean-studio": "清新影棚",
  "guide.url-to-video.style.cinematic-luxury": "电影感奢华",
  "guide.url-to-video.style.minimalist-premium": "极简高级",
  "guide.url-to-video.style.natural-lifestyle": "自然生活",
  "guide.url-to-video.style.bold-colorful": "鲜亮大胆",
  "guide.url-to-video.style.futuristic-tech": "未来科技",
  "guide.url-to-video.style.ugc-style": "真实口播",
  "guide.url-to-video.style.unboxing": "开箱测评",
  "guide.url-to-video.style.street-style": "街头潮流",

  // 复刻爆款视频（重现病毒式广告）模态框文案
  "guide.recreate-viral-ads.modal.title": "重现病毒式广告",
  "guide.recreate-viral-ads.modal.subtitle": "重现视频结构，或替换人物和产品，同时保留原始创意。",
  "guide.recreate-viral-ads.clone-mode.label": "克隆模式",
  "guide.recreate-viral-ads.mode.recreate-structure.title": "重现结构",
  "guide.recreate-viral-ads.mode.recreate-structure.desc": "保留分镜、节奏与结构，创作全新内容。",
  "guide.recreate-viral-ads.mode.replace-elements.title": "替换元素",
  "guide.recreate-viral-ads.mode.replace-elements.desc": "替换人物或产品，其余部分保持不变。",
  "guide.recreate-viral-ads.target-video.label": "目标视频",
  "guide.recreate-viral-ads.target-video.required": "必填",
  "guide.recreate-viral-ads.target-video.add": "添加目标视频",
  "guide.recreate-viral-ads.target-video.hint": "仅限 MP4 · 最大 50 MB · 2-60 秒",
  "guide.recreate-viral-ads.prompt-input.label": "新视频展示什么内容？",
  "guide.recreate-viral-ads.prompt-input.placeholder": "描述新的主体、场景、信息或需要替换的元素...",
  "guide.recreate-viral-ads.reference-materials.label": "其他参考素材",
  "guide.recreate-viral-ads.reference-materials.optional": "可选",
  "guide.recreate-viral-ads.reference-materials.add": "添加其他参考素材",
  "guide.recreate-viral-ads.reference-materials.hint": "添加产品、人物、品牌或视觉参考素材。",
  "guide.recreate-viral-ads.reference-materials.limit": "最多 6 个文件",
  "guide.recreate-viral-ads.submit-btn": "开始制作 →",
  "guide.recreate-viral-ads.video-required": "请先添加目标视频",
  "guide.recreate-viral-ads.video-format-error": "仅支持 MP4 格式视频文件",
  "guide.recreate-viral-ads.video-size-error": "视频文件大小不能超过 50 MB",
  "guide.recreate-viral-ads.applied": "已生成病毒式广告复刻任务草稿",

  // 批量创建广告（Bulk Create Ads）模态框文案
  "guide.bulk-create-ads.modal.title": "批量创建广告",
  "guide.bulk-create-ads.modal.subtitle": "针对不同格式、时长和创意角度，批量生成多条广告变体。",
  "guide.bulk-create-ads.creative-brief.label": "创意简报",
  "guide.bulk-create-ads.creative-brief.placeholder": "描述产品、开头钩子、卖点优势和行动号召...",
  "guide.bulk-create-ads.references.label": "参考素材",
  "guide.bulk-create-ads.references.optional": "可选",
  "guide.bulk-create-ads.references.add": "添加参考素材",
  "guide.bulk-create-ads.references.hint": "上传产品图片、包装或简短参考片段。",
  "guide.bulk-create-ads.references.limit": "最多 6 个文件",
  "guide.bulk-create-ads.aspect-ratio.label": "画幅比例",
  "guide.bulk-create-ads.duration.label": "目标时长",
  "guide.bulk-create-ads.video-count.label": "生成视频数量",
  "guide.bulk-create-ads.video-count.desc": "基于同一份创意简报生成 1~10 条创意变体广告方案。",
  "guide.bulk-create-ads.submit-btn": "生成批量创意方案 →",
  "guide.bulk-create-ads.brief-required": "请先填写创意简报",
  "guide.bulk-create-ads.applied": "已生成批量广告制作任务草稿",

  // 爆款对标与一键复刻（Trending Videos, Ready to Replicate）
  "guide.tabs.label": "创作发现",
  "guide.tab.trending": "创作灵感",
  "guide.tab.skills": "Skill",
  "skills.subtitle": "精选热门实用技能，一键填入指令即刻对话出片。",
  "skills.category.all": "精选",
  "skills.category.sk-commerce": "电商变现",
  "skills.category.sk-marketing": "营销增长",
  "skills.category.sk-office": "协作办公",
  "skills.category.sk-visual": "视觉与视频",
  "skills.category.sk-writing": "内容创作",
  "skills.chips.label": "技能分类筛选",
  "skills.card.use": "使用 Skill",
  "skills.source.badge": "精选工坊",
  "skills.empty": "当前分类下暂无技能。",
  "trending.title": "爆款对标视频，随时复刻",
  "trending.subtitle": "挑选值得复刻的爆款结构，一键接管输入框直接出片。",
  "trending.source.badge": "来自灵感库",
  "trending.source.hint": "取自灵感社区里已导入的对标视频，按播放量排列。",
  "trending.filters.label": "爆款筛选条件",
  "trending.filter.region": "地区",
  "trending.filter.industry": "类目",
  "trending.filter.views": "播放量",
  "trending.filter.engagement": "互动率",
  "trending.filter.range": "发布时间窗",
  "trending.filter.sort": "排序方式",
  "trending.filter.reset": "重置筛选",
  "trending.region.all": "全部地区",
  "trending.industry.all": "全部类目",
  "trending.views.all": "播放量",
  "trending.views.100k": "播放 100K+",
  "trending.views.1m": "播放 1M+",
  "trending.views.5m": "播放 5M+",
  "trending.views.10m": "播放 10M+",
  "trending.engagement.all": "互动率",
  "trending.engagement.0_5": "互动率 0.5%+",
  "trending.engagement.1": "互动率 1%+",
  "trending.engagement.2": "互动率 2%+",
  "trending.range.all": "全部时间",
  "trending.range.d7": "近 7 天发布",
  "trending.range.d30": "近 30 天发布",
  "trending.range.d90": "近 90 天发布",
  "trending.info.range": "按作品发布时间筛选；库里没有发布时间的作品不计入时间窗。",
  "trending.sort.recommend": "排序：智能推荐",
  "trending.sort.views": "排序：播放量",
  "trending.sort.engagement": "排序：互动率",
  "trending.info.engagement": "互动总量与播放量之比。",
  "trending.metric.engagement": "互动率",
  "trending.metric.views": "播放量",
  "trending.card.recreate": "复刻",
  "trending.loading": "正在读取灵感库里的对标视频…",
  "trending.feed.loading": "正在加载更多对标视频…",
  "trending.feed.hint": "继续下滑，自动加载更多",
  "trending.feed.end": "已经到底，灵感库里的对标视频都在这儿了",
  "trending.retry": "重试",
  "trending.empty": "当前筛选条件下没有匹配的对标视频。",
  "trending.library.empty": "灵感库里还没有可复刻的对标视频。",
  "trending.library.emptyHint": "去灵感社区导入对标视频链接后，这里会自动出现。",
  "trending.library.unavailable": "暂时读不到灵感库。",
  "trending.library.unavailableHint": "灵感社区未就绪时这里不展示任何数据——不拿示例充数。",
  "trending.undock": "收起输入框",

  // 精选 Skill 双语名称与描述
  "skills.locale": "zh",
  "locale": "zh",
  "skill.name.sk-omx-3d-animation-short-generator": "3D动画短片",
  "skill.name.3d-animation-short-generator": "3D动画短片",
  "skill.desc.sk-omx-3d-animation-short-generator": "根据故事创意完成角色场景设定、镜头规划、分镜生成与视频合成，输出风格统一的3D动画短片。",
  "skill.desc.3d-animation-short-generator": "根据故事创意完成角色场景设定、镜头规划、分镜生成与视频合成，输出风格统一的3D动画短片。",
  "skill.name.sk-omx-brand-promo-video-generator": "品牌宣传短片生成器",
  "skill.name.brand-promo-video-generator": "品牌宣传短片生成器",
  "skill.desc.sk-omx-brand-promo-video-generator": "基于品牌素材与推广目标，完成事实核验、创意方向、分镜和音画合成，输出可展示的品牌宣传短片。",
  "skill.desc.brand-promo-video-generator": "基于品牌素材与推广目标，完成事实核验、创意方向、分镜和音画合成，输出可展示的品牌宣传短片。",
  "skill.name.sk-omx-minimalist-product-ad-generator": "极简产品广告生成器",
  "skill.name.minimalist-product-ad-generator": "极简产品广告生成器",
  "skill.desc.sk-omx-minimalist-product-ad-generator": "完成卖点提炼与节拍分镜设计，输出极简美学产品广告短片。",
  "skill.desc.minimalist-product-ad-generator": "完成卖点提炼与节拍分镜设计，输出极简美学产品广告短片。",
  "skill.name.sk-omx-music-video-subtitle-generator": "音乐MV动态字幕生成器",
  "skill.name.music-video-subtitle-generator": "音乐MV动态字幕生成器",
  "skill.desc.sk-omx-music-video-subtitle-generator": "基于音乐和歌词完成节奏拆解、镜头设计与动态字幕方案。",
  "skill.desc.music-video-subtitle-generator": "基于音乐和歌词完成节奏拆解、镜头设计与动态字幕方案。",
  "skill.name.sk-omx-paper-collage-explainer-generator": "纸拼贴讲解动画",
  "skill.name.paper-collage-explainer-generator": "纸拼贴讲解动画",
  "skill.desc.sk-omx-paper-collage-explainer-generator": "将文案与抽象概念转成触感质感的纸拼贴定格讲解动画。",
  "skill.desc.paper-collage-explainer-generator": "将文案与抽象概念转成触感质感的纸拼贴定格讲解动画。",
  "skill.name.sk-omx-fpv-tour-video-generator": "第一视角 FPV 穿越生成",
  "skill.name.fpv-tour-video-generator": "第一视角 FPV 穿越生成",
  "skill.desc.sk-omx-fpv-tour-video-generator": "按场景空间决定路线几何，生成连续沉浸的第一人称 FPV 一镜到底穿越视频。",
  "skill.desc.fpv-tour-video-generator": "按场景空间决定路线几何，生成连续沉浸的第一人称 FPV 一镜到底穿越视频。",
  "skill.name.sk-omx-pov-short-film-generator": "第一视角短片生成",
  "skill.name.pov-short-film-generator": "第一视角短片生成",
  "skill.desc.sk-omx-pov-short-film-generator": "规划主角第一人称视角的沉浸式短片制作方案。",
  "skill.desc.pov-short-film-generator": "规划主角第一人称视角的沉浸式短片制作方案。",
  "skill.name.sk-omx-suspense-title-sequence-generator": "悬疑电影片头生成",
  "skill.name.suspense-title-sequence-generator": "悬疑电影片头生成",
  "skill.desc.sk-omx-suspense-title-sequence-generator": "锚定关键帧和艺术署名，生成复古悬疑美学电影片头成片。",
  "skill.desc.suspense-title-sequence-generator": "锚定关键帧和艺术署名，生成复古悬疑美学电影片头成片。",
  "skill.name.sk-amazon-keyword-traffic-analysis": "亚马逊关键词流量分析",
  "skill.name.amazon-keyword-traffic-analysis": "亚马逊关键词流量分析",
  "skill.desc.sk-amazon-keyword-traffic-analysis": "亚马逊关键词、流量来源、ABA 趋势与 PPC 广告机会分析。",
  "skill.desc.amazon-keyword-traffic-analysis": "亚马逊关键词、流量来源、ABA 趋势与 PPC 广告机会分析。",
  "skill.name.sk-amazon-listing-optimization": "亚马逊 Listing 优化",
  "skill.name.amazon-listing-optimization": "亚马逊 Listing 优化",
  "skill.desc.sk-amazon-listing-optimization": "亚马逊 Listing 文案、A+ 页面规划与关键词覆盖度优化。",
  "skill.desc.amazon-listing-optimization": "亚马逊 Listing 文案、A+ 页面规划与关键词覆盖度优化。",
  "skill.name.sk-amazon-market-analysis": "亚马逊市场分析",
  "skill.name.amazon-market-analysis": "亚马逊市场分析",
  "skill.desc.sk-amazon-market-analysis": "使用 amazon-mcp 进行亚马逊品类与市场机会深度分析。",
  "skill.desc.amazon-market-analysis": "使用 amazon-mcp 进行亚马逊品类与市场机会深度分析。",
  "skill.name.sk-amazon-product-analysis": "亚马逊产品分析",
  "skill.name.amazon-product-analysis": "亚马逊产品分析",
  "skill.desc.sk-amazon-product-analysis": "使用 amazon-mcp 及输入文件进行亚马逊 ASIN、SKU 与竞品研究。",
  "skill.desc.amazon-product-analysis": "使用 amazon-mcp 及输入文件进行亚马逊 ASIN、SKU 与竞品研究。",
  "skill.name.sk-amazon-review-optimization": "亚马逊评论优化",
  "skill.name.amazon-review-optimization": "亚马逊评论优化",
  "skill.desc.sk-amazon-review-optimization": "亚马逊买家书面评论、VOC 声量、QA 问答与用户痛点深度优化。",
  "skill.desc.amazon-review-optimization": "亚马逊买家书面评论、VOC 声量、QA 问答与用户痛点深度优化。",
  "skill.name.sk-amazon-trend-risk-monitor": "亚马逊趋势风险监控",
  "skill.name.amazon-trend-risk-monitor": "亚马逊趋势风险监控",
  "skill.desc.sk-amazon-trend-risk-monitor": "亚马逊热度趋势、BSR 榜单、销量预测与商标侵权风险监控。",
  "skill.desc.amazon-trend-risk-monitor": "亚马逊热度趋势、BSR 榜单、销量预测与商标侵权风险监控。",
  "skill.name.sk-bggg-data-amazon": "BGGG Amazon 评论采集",
  "skill.name.bggg-data-amazon": "BGGG Amazon 评论采集",
  "skill.desc.sk-bggg-data-amazon": "采集 Amazon US 公开书面评论，保留尝试与错误记录并归一化为可追溯 JSONL，为 VOC 分析提供输入。",
  "skill.desc.bggg-data-amazon": "采集 Amazon US 公开书面评论，保留尝试与错误记录并归一化为可追溯 JSONL，为 VOC 分析提供输入。",
  "skill.name.sk-ecommerce-daily-review": "电商日报复盘",
  "skill.name.ecommerce-daily-review": "电商日报复盘",
  "skill.desc.sk-ecommerce-daily-review": "面向亚马逊和 TikTok Shop 运营的每日与每周复盘模板。",
  "skill.desc.ecommerce-daily-review": "面向亚马逊和 TikTok Shop 运营的每日与每周复盘模板。",
  "skill.name.sk-ecommerce-output-spec": "电商输出规范",
  "skill.name.ecommerce-output-spec": "电商输出规范",
  "skill.desc.sk-ecommerce-output-spec": "电商运营 Agent 的共享报表与文件输出交付规范。",
  "skill.desc.ecommerce-output-spec": "电商运营 Agent 的共享报表与文件输出交付规范。",
  "skill.name.sk-ecommerce-routing-policy": "电商路由策略",
  "skill.name.ecommerce-routing-policy": "电商路由策略",
  "skill.desc.sk-ecommerce-routing-policy": "电商运营 Agent 的共享任务路由规则与分流策略。",
  "skill.desc.ecommerce-routing-policy": "电商运营 Agent 的共享任务路由规则与分流策略。",
  "skill.name.sk-html-report-templates": "HTML 报表模板",
  "skill.name.html-report-templates": "HTML 报表模板",
  "skill.desc.sk-html-report-templates": "用于 html-writer 的复制即用 HTML 报表与仪表盘模板。",
  "skill.desc.html-report-templates": "用于 html-writer 的复制即用 HTML 报表与仪表盘模板。",
  "skill.name.sk-omx-2d-animation-commentary-drama": "2D动画半解说短剧",
  "skill.name.2d-animation-commentary-drama": "2D动画半解说短剧",
  "skill.desc.sk-omx-2d-animation-commentary-drama": "结合2D二次元画风与解说旁白的短剧生成器，支持分镜与节奏剪辑一键输出。",
  "skill.desc.2d-animation-commentary-drama": "结合2D二次元画风与解说旁白的短剧生成器，支持分镜与节奏剪辑一键输出。",
  "skill.name.sk-omx-3d-comic-commentary-drama": "3D漫剧半解说",
  "skill.name.3d-comic-commentary-drama": "3D漫剧半解说",
  "skill.desc.sk-omx-3d-comic-commentary-drama": "3D漫剧半解说视频生成工作流，自动完成分镜调度、动作与音轨合成。",
  "skill.desc.3d-comic-commentary-drama": "3D漫剧半解说视频生成工作流，自动完成分镜调度、动作与音轨合成。",
  "skill.name.sk-omx-asmr-ambient": "助眠音频",
  "skill.name.asmr-ambient": "助眠音频",
  "skill.desc.sk-omx-asmr-ambient": "生成助眠冥想与ASMR音频。",
  "skill.desc.asmr-ambient": "生成助眠冥想与ASMR音频。",
  "skill.name.sk-omx-audiobook": "有声书",
  "skill.name.audiobook": "有声书",
  "skill.desc.sk-omx-audiobook": "把书籍转化为多角色有声书。",
  "skill.desc.audiobook": "把书籍转化为多角色有声书。",
  "skill.name.sk-omx-brand-stream-mg": "品牌流线 MG 动效",
  "skill.name.brand-stream-mg": "品牌流线 MG 动效",
  "skill.desc.sk-omx-brand-stream-mg": "基于Logo与主题生成IP领航的品牌流线MG动效视频，适合新品发布预热与社媒传播。",
  "skill.desc.brand-stream-mg": "基于Logo与主题生成IP领航的品牌流线MG动效视频，适合新品发布预热与社媒传播。",
  "skill.name.sk-omx-chinese-style-short-drama-generator": "国风短剧成片生成器",
  "skill.name.chinese-style-short-drama-generator": "国风短剧成片生成器",
  "skill.desc.sk-omx-chinese-style-short-drama-generator": "国风短剧全流程成片创作。",
  "skill.desc.chinese-style-short-drama-generator": "国风短剧全流程成片创作。",
  "skill.name.sk-omx-clip-export": "剪映导出",
  "skill.name.clip-export": "剪映导出",
  "skill.desc.sk-omx-clip-export": "把视频推送到剪映或CapCut草稿。",
  "skill.desc.clip-export": "把视频推送到剪映或CapCut草稿。",
  "skill.name.sk-omx-co-op-game-intro-generator": "双人游戏开场视频生成器",
  "skill.name.co-op-game-intro-generator": "双人游戏开场视频生成器",
  "skill.desc.sk-omx-co-op-game-intro-generator": "根据玩家名称、视觉风格和角色参考图，生成双人游戏菜单开场视频。",
  "skill.desc.co-op-game-intro-generator": "根据玩家名称、视觉风格和角色参考图，生成双人游戏菜单开场视频。",
  "skill.name.sk-omx-digital-product-promo-generator": "数字产品宣传片生成",
  "skill.name.digital-product-promo-generator": "数字产品宣传片生成",
  "skill.desc.sk-omx-digital-product-promo-generator": "把真实产品页面、前端项目与用户动效参考转成可审片的电影感宣传片，准确呈现界面、运镜、节奏和声音。",
  "skill.desc.digital-product-promo-generator": "把真实产品页面、前端项目与用户动效参考转成可审片的电影感宣传片，准确呈现界面、运镜、节奏和声音。",
  "skill.name.sk-omx-dot-matrix-brand-wordmark-motion": "点阵品牌字形动效",
  "skill.name.dot-matrix-brand-wordmark-motion": "点阵品牌字形动效",
  "skill.desc.sk-omx-dot-matrix-brand-wordmark-motion": "根据品牌 Logo、品牌名与标语生成点阵品牌字形动效视频与横版品牌图。",
  "skill.desc.dot-matrix-brand-wordmark-motion": "根据品牌 Logo、品牌名与标语生成点阵品牌字形动效视频与横版品牌图。",
  "skill.name.sk-omx-drama-soundtrack": "影视配乐",
  "skill.name.drama-soundtrack": "影视配乐",
  "skill.desc.sk-omx-drama-soundtrack": "创作角色主题曲与场景配乐。",
  "skill.desc.drama-soundtrack": "创作角色主题曲与场景配乐。",
  "skill.name.sk-omx-ecommerce-design": "电商图设计",
  "skill.name.ecommerce-design": "电商图设计",
  "skill.desc.sk-omx-ecommerce-design": "覆盖多品类的专业电商详情页与主图设计。",
  "skill.desc.ecommerce-design": "覆盖多品类的专业电商详情页与主图设计。",
  "skill.name.sk-omx-ecommerce-image": "电商商品图",
  "skill.name.ecommerce-image": "电商商品图",
  "skill.desc.sk-omx-ecommerce-image": "从实拍图生成平台合规的高品质电商组图。",
  "skill.desc.ecommerce-image": "从实拍图生成平台合规的高品质电商组图。",
  "skill.name.sk-omx-education-studio": "教育内容工作室",
  "skill.name.education-studio": "教育内容工作室",
  "skill.desc.sk-omx-education-studio": "教育内容与教育视频的一体化创作入口，覆盖讲解、课件与教学视频。",
  "skill.desc.education-studio": "教育内容与教育视频的一体化创作入口，覆盖讲解、课件与教学视频。",
  "skill.name.sk-omx-fashion-scene-showcase-video": "时装场景展示视频",
  "skill.name.fashion-scene-showcase-video": "时装场景展示视频",
  "skill.desc.sk-omx-fashion-scene-showcase-video": "高定服装与潮牌模特动态展示短视频生成器，支持秀场T台走秀与面料光影细节。",
  "skill.desc.fashion-scene-showcase-video": "高定服装与潮牌模特动态展示短视频生成器，支持秀场T台走秀与面料光影细节。",
  "skill.name.sk-omx-felt-stop-motion-story-short": "羊毛毡故事短片",
  "skill.name.felt-stop-motion-story-short": "羊毛毡故事短片",
  "skill.desc.sk-omx-felt-stop-motion-story-short": "温暖治愈的定格毛毡动画短片生成器，支持柔软织物纹理与治愈童话配乐。",
  "skill.desc.felt-stop-motion-story-short": "温暖治愈的定格毛毡动画短片生成器，支持柔软织物纹理与治愈童话配乐。",
  "skill.name.sk-omx-film-reference-prompt-writer": "电影质感提示词大师",
  "skill.name.film-reference-prompt-writer": "电影质感提示词大师",
  "skill.desc.sk-omx-film-reference-prompt-writer": "从电影名称、剧照或截图提炼可复用的视觉与镜头规则，生成专业图像与视频提示词。",
  "skill.desc.film-reference-prompt-writer": "从电影名称、剧照或截图提炼可复用的视觉与镜头规则，生成专业图像与视频提示词。",
  "skill.name.sk-omx-h3-prompt-expert": "H3 提示词专家",
  "skill.name.h3-prompt-expert": "H3 提示词专家",
  "skill.desc.sk-omx-h3-prompt-expert": "将零散需求与参考素材整理成可控的多模态视频生成精准指令。",
  "skill.desc.h3-prompt-expert": "将零散需求与参考素材整理成可控的多模态视频生成精准指令。",
  "skill.name.sk-omx-h3-visual-design": "H3 视觉动态设计",
  "skill.name.h3-visual-design": "H3 视觉动态设计",
  "skill.desc.sk-omx-h3-visual-design": "字体、Logo、版式与空间动态包装设计。",
  "skill.desc.h3-visual-design": "字体、Logo、版式与空间动态包装设计。",
  "skill.name.sk-omx-handdrawn-live-video-generator": "手绘实拍融合视频生成器",
  "skill.name.handdrawn-live-video-generator": "手绘实拍融合视频生成器",
  "skill.desc.sk-omx-handdrawn-live-video-generator": "生成手绘动画与实拍接触变形的创意短片视频。",
  "skill.desc.handdrawn-live-video-generator": "生成手绘动画与实拍接触变形的创意短片视频。",
  "skill.name.sk-omx-ip-toy-grid-motion": "IP潮玩六宫格动态海报",
  "skill.name.ip-toy-grid-motion": "IP潮玩六宫格动态海报",
  "skill.desc.sk-omx-ip-toy-grid-motion": "基于角色形象生成3D潮玩六宫格竖版动态视频，适合IP提案与社媒展示。",
  "skill.desc.ip-toy-grid-motion": "基于角色形象生成3D潮玩六宫格竖版动态视频，适合IP提案与社媒展示。",
  "skill.name.sk-omx-line-doodle-explainer-generator": "线条图解科普视频生成",
  "skill.name.line-doodle-explainer-generator": "线条图解科普视频生成",
  "skill.desc.sk-omx-line-doodle-explainer-generator": "根据知识主题或教材内容，生成线条小人图解科普视频方案与成片素材。",
  "skill.desc.line-doodle-explainer-generator": "根据知识主题或教材内容，生成线条小人图解科普视频方案与成片素材。",
  "skill.name.sk-omx-lip-product-ad-generator": "唇部彩妆广告生成",
  "skill.name.lip-product-ad-generator": "唇部彩妆广告生成",
  "skill.desc.sk-omx-lip-product-ad-generator": "生成唇部彩妆高质感商业广告TVC，强化人物与产品的自然互动。",
  "skill.desc.lip-product-ad-generator": "生成唇部彩妆高质感商业广告TVC，强化人物与产品的自然互动。",
  "skill.name.sk-omx-live-action-commentary-drama": "半解说真人短剧",
  "skill.name.live-action-commentary-drama": "半解说真人短剧",
  "skill.desc.sk-omx-live-action-commentary-drama": "真人短剧半解说成片助手，拆解剧情爽点、黄金3秒开场与强反转旁白设计。",
  "skill.desc.live-action-commentary-drama": "真人短剧半解说成片助手，拆解剧情爽点、黄金3秒开场与强反转旁白设计。",
  "skill.name.sk-omx-micro-expression-video-generator": "人物微表情视频生成",
  "skill.name.micro-expression-video-generator": "人物微表情视频生成",
  "skill.desc.sk-omx-micro-expression-video-generator": "根据角色图与剧本设计分时微表情提示词，塑造自然可信的人物表演。",
  "skill.desc.micro-expression-video-generator": "根据角色图与剧本设计分时微表情提示词，塑造自然可信的人物表演。",
  "skill.name.sk-omx-papercraft-stop-motion-explainer": "纸艺定格科普视频生成器",
  "skill.name.papercraft-stop-motion-explainer": "纸艺定格科普视频生成器",
  "skill.desc.sk-omx-papercraft-stop-motion-explainer": "设计纸偶、分层布景与分镜，输出纸艺定格科普短片。",
  "skill.desc.papercraft-stop-motion-explainer": "设计纸偶、分层布景与分镜，输出纸艺定格科普短片。",
  "skill.name.sk-omx-product-kinetic-typography-tvc": "产品贴字动画TVC",
  "skill.name.product-kinetic-typography-tvc": "产品贴字动画TVC",
  "skill.desc.sk-omx-product-kinetic-typography-tvc": "商业广告级产品贴字与动效排版TVC生成器，融合动态文字跟拍与快节奏卖点展示。",
  "skill.desc.product-kinetic-typography-tvc": "商业广告级产品贴字与动效排版TVC生成器，融合动态文字跟拍与快节奏卖点展示。",
  "skill.name.sk-omx-retro-city-cel-animation-short": "复古都市赛璐璐短片",
  "skill.name.retro-city-cel-animation-short": "复古都市赛璐璐短片",
  "skill.desc.sk-omx-retro-city-cel-animation-short": "90年代复古都市赛璐璐动画生成器，包含颗粒噪点、霓虹色调与CityPop氛围感。",
  "skill.desc.retro-city-cel-animation-short": "90年代复古都市赛璐璐动画生成器，包含颗粒噪点、霓虹色调与CityPop氛围感。",
  "skill.name.sk-omx-scifi-cinematic-video-generator": "未来科幻质感影视生成器",
  "skill.name.scifi-cinematic-video-generator": "未来科幻质感影视生成器",
  "skill.desc.sk-omx-scifi-cinematic-video-generator": "赛博朋克与硬科幻质感影视生成器，强化光影粒子、体积雾与未来机械细节。",
  "skill.desc.scifi-cinematic-video-generator": "赛博朋克与硬科幻质感影视生成器，强化光影粒子、体积雾与未来机械细节。",
  "skill.name.sk-omx-short-drama-multilingual-dubbing": "短剧多语言出海配音",
  "skill.name.short-drama-multilingual-dubbing": "短剧多语言出海配音",
  "skill.desc.sk-omx-short-drama-multilingual-dubbing": "分离人声与背景音并复刻音色节奏，输出多语言出海配音视频与字幕。",
  "skill.desc.short-drama-multilingual-dubbing": "分离人声与背景音并复刻音色节奏，输出多语言出海配音视频与字幕。",
  "skill.name.sk-omx-short-drama-screenwriter": "短剧编剧助手",
  "skill.name.short-drama-screenwriter": "短剧编剧助手",
  "skill.desc.sk-omx-short-drama-screenwriter": "按选题与爆款节奏撰写完整短剧剧本。",
  "skill.desc.short-drama-screenwriter": "按选题与爆款节奏撰写完整短剧剧本。",
  "skill.name.sk-omx-short-drama-series-writer": "微短剧剧集编剧",
  "skill.name.short-drama-series-writer": "微短剧剧集编剧",
  "skill.desc.sk-omx-short-drama-series-writer": "一键生成微短剧全流程系列剧本与角色设定。",
  "skill.desc.short-drama-series-writer": "一键生成微短剧全流程系列剧本与角色设定。",
  "skill.name.sk-omx-silkscreen-decorative-illustration-short": "丝印装饰插画风格短片",
  "skill.name.silkscreen-decorative-illustration-short": "丝印装饰插画风格短片",
  "skill.desc.sk-omx-silkscreen-decorative-illustration-short": "将丝印装饰插画转成艺术音效短片，适合高端奢华叙事。",
  "skill.desc.silkscreen-decorative-illustration-short": "将丝印装饰插画转成艺术音效短片，适合高端奢华叙事。",
  "skill.name.sk-omx-sitcom-story-video-generator": "情景喜剧故事视频",
  "skill.name.sitcom-story-video-generator": "情景喜剧故事视频",
  "skill.desc.sk-omx-sitcom-story-video-generator": "情景喜剧风格故事视频生成助手，涵盖多机位切换与喜剧冲突。",
  "skill.desc.sitcom-story-video-generator": "情景喜剧风格故事视频生成助手，涵盖多机位切换与喜剧冲突。",
  "skill.name.sk-omx-subtitle-correction": "字幕修正",
  "skill.name.subtitle-correction": "字幕修正",
  "skill.desc.sk-omx-subtitle-correction": "修正 SRT 字幕语音识别错误，严格保留时间轴和编号。",
  "skill.desc.subtitle-correction": "修正 SRT 字幕语音识别错误，严格保留时间轴和编号。",
  "skill.name.sk-omx-transcript-broll-planner": "口播视频B-roll规划器",
  "skill.name.transcript-broll-planner": "口播视频B-roll规划器",
  "skill.desc.sk-omx-transcript-broll-planner": "把口播逐字稿按语义拆成精准的 B-roll 画面方案并生成素材。",
  "skill.desc.transcript-broll-planner": "把口播逐字稿按语义拆成精准的 B-roll 画面方案并生成素材。",
  "skill.name.sk-omx-video-deconstruct": "视频拆解与复刻",
  "skill.name.video-deconstruct": "视频拆解与复刻",
  "skill.desc.sk-omx-video-deconstruct": "拆解爆款视频镜头、运镜、声音并编译为可复刻的最终 Prompt 与制作计划。",
  "skill.desc.video-deconstruct": "拆解爆款视频镜头、运镜、声音并编译为可复刻的最终 Prompt 与制作计划。",
  "skill.name.sk-omx-video-deconstruct-analyzer": "视频拆解分析师",
  "skill.name.video-deconstruct-analyzer": "视频拆解分析师",
  "skill.desc.sk-omx-video-deconstruct-analyzer": "高密度深度拆解 AI 视频的镜头语言与生成参数。",
  "skill.desc.video-deconstruct-analyzer": "高密度深度拆解 AI 视频的镜头语言与生成参数。",
  "skill.name.sk-omx-vox-style-video-generator": "Vox风格科普动画",
  "skill.name.vox-style-video-generator": "Vox风格科普动画",
  "skill.desc.sk-omx-vox-style-video-generator": "生成带字幕、旁白与背景音乐的剪贴拼贴风格科普动画成片。",
  "skill.desc.vox-style-video-generator": "生成带字幕、旁白与背景音乐的剪贴拼贴风格科普动画成片。",
  "skill.name.sk-omx-wes-anderson-aesthetic-generator": "韦斯·安德森美学短片生成器",
  "skill.name.wes-anderson-aesthetic-generator": "韦斯·安德森美学短片生成器",
  "skill.desc.sk-omx-wes-anderson-aesthetic-generator": "严格对齐韦斯·安德森对称构图、复古调色与平移运镜美学的电影感短片生成器。",
  "skill.desc.wes-anderson-aesthetic-generator": "严格对齐韦斯·安德森对称构图、复古调色与平移运镜美学的电影感短片生成器。",
  "skill.name.sk-shopee-brand-analysis": "Shopee 品牌分析",
  "skill.name.shopee-brand-analysis": "Shopee 品牌分析",
  "skill.desc.sk-shopee-brand-analysis": "使用 shopee-mcp 分析 Shopee 品牌排名、详情、趋势、商品组合及站点/类别分布。",
  "skill.desc.shopee-brand-analysis": "使用 shopee-mcp 分析 Shopee 品牌排名、详情、趋势、商品组合及站点/类别分布。",
  "skill.name.sk-shopee-keyword-analysis": "Shopee 关键词分析",
  "skill.name.shopee-keyword-analysis": "Shopee 关键词分析",
  "skill.desc.sk-shopee-keyword-analysis": "使用 shopee-mcp 进行 Shopee 热搜词排名、详情、趋势及关联商品分析。",
  "skill.desc.shopee-keyword-analysis": "使用 shopee-mcp 进行 Shopee 热搜词排名、详情、趋势及关联商品分析。",
  "skill.name.sk-shopee-market-analysis": "Shopee 市场分析",
  "skill.name.shopee-market-analysis": "Shopee 市场分析",
  "skill.desc.sk-shopee-market-analysis": "使用 shopee-mcp 进行 Shopee 站点与品类市场机会分析。",
  "skill.desc.shopee-market-analysis": "使用 shopee-mcp 进行 Shopee 站点与品类市场机会分析。",
  "skill.name.sk-shopee-product-analysis": "Shopee 商品分析",
  "skill.name.shopee-product-analysis": "Shopee 商品分析",
  "skill.desc.sk-shopee-product-analysis": "使用 shopee-mcp 进行 Shopee 商品排行、详情、趋势与热词分析。",
  "skill.desc.shopee-product-analysis": "使用 shopee-mcp 进行 Shopee 商品排行、详情、趋势与热词分析。",
  "skill.name.sk-shopee-shop-analysis": "Shopee 店铺分析",
  "skill.name.shopee-shop-analysis": "Shopee 店铺分析",
  "skill.desc.sk-shopee-shop-analysis": "使用 shopee-mcp 进行 Shopee 店铺排行、详情、趋势、选品与品牌组合分析。",
  "skill.desc.shopee-shop-analysis": "使用 shopee-mcp 进行 Shopee 店铺排行、详情、趋势、选品与品牌组合分析。",
  "skill.name.sk-tiktok-market-trend-analysis": "TikTok 市场趋势分析",
  "skill.name.tiktok-market-trend-analysis": "TikTok 市场趋势分析",
  "skill.desc.sk-tiktok-market-trend-analysis": "使用 Topview td 工具分析 TikTok Shop 区域、品类、商品与卖家趋势。",
  "skill.desc.tiktok-market-trend-analysis": "使用 Topview td 工具分析 TikTok Shop 区域、品类、商品与卖家趋势。",
  "skill.name.sk-tiktok-material-breakdown": "TikTok 素材拆解",
  "skill.name.tiktok-material-breakdown": "TikTok 素材拆解",
  "skill.desc.sk-tiktok-material-breakdown": "TikTok 爆款短视频素材、开头黄金 Hook 与行动号召 CTA 逐秒拆解。",
  "skill.desc.tiktok-material-breakdown": "TikTok 爆款短视频素材、开头黄金 Hook 与行动号召 CTA 逐秒拆解。",
  "skill.name.sk-tiktok-product-selection": "TikTok 选品",
  "skill.name.tiktok-product-selection": "TikTok 选品",
  "skill.desc.sk-tiktok-product-selection": "TikTok Shop 爆款潜力商品挖掘、筛选与综合评分。",
  "skill.desc.tiktok-product-selection": "TikTok Shop 爆款潜力商品挖掘、筛选与综合评分。",
  "skill.name.sk-tiktok-script-creation": "TikTok 脚本创作",
  "skill.name.tiktok-script-creation": "TikTok 脚本创作",
  "skill.desc.sk-tiktok-script-creation": "TikTok UGC 口播、达人种草、品牌广告与直播带货脚本生成。",
  "skill.desc.tiktok-script-creation": "TikTok UGC 口播、达人种草、品牌广告与直播带货脚本生成。",
  "skill.name.sk-video-generate-canvas": "视频生成画布",
  "skill.name.video-generate-canvas": "视频生成画布",
  "skill.desc.sk-video-generate-canvas": "当用户表达任何视频创作意图时触发此技能，如在画布中生成或编辑视频。",
  "skill.desc.video-generate-canvas": "当用户表达任何视频创作意图时触发此技能，如在画布中生成或编辑视频。",
}

export const guideEn = {
  "guide.title": "Start a marketing task",
  "guide.market-insights": "Market Insights",
  "guide.listing-reviews": "Listing & Reviews",
  "guide.content-creators": "Content & Creators",
  "guide.ad-analytics": "Ad Analytics",
  "guide.category-opportunity.title": "Category Opportunity",
  "guide.category-opportunity.prompt": "Analyze the potential of [product category] on [ecommerce platform] in [target market]. Evaluate demand, competition, pricing, customer needs, barriers to entry, and growth signals; clearly distinguish facts, inferences, and assumptions; and recommend whether and how to enter. If context is missing, ask an open follow-up question about any useful reference information.",
  "guide.trending-products.title": "Trending Products",
  "guide.trending-products.prompt": "Identify trending products with strong sales potential in [category/product] on [ecommerce platform] in [target market], taking [business context or constraints] into account. Explain the demand signals, audience fit, competitive intensity, pricing opportunity, seasonality, and operational risks behind each recommendation. If context is missing, ask an open follow-up question about useful reference information.",
  "guide.competitor-scan.title": "Competitor Scan",
  "guide.competitor-scan.prompt": "Analyze the top-ranking competitor product listings for [benchmark product/category] on [ecommerce platform] in [target market]. Compare positioning, pricing, offers, reviews, content, selling points, and conversion tactics, then identify specific opportunities for differentiation. If context is missing, ask an open follow-up question about useful reference information.",
  "guide.title-optimization.title": "Title Optimization",
  "guide.title-optimization.prompt": "Optimize [current product title] for [ecommerce platform] using [product://product details]. Improve search visibility, keyword relevance, readability, differentiation, and conversion while following the platform’s requirements. Provide the recommended title with a concise rationale. If context is missing, ask an open follow-up question about useful product information.",
  "guide.review-insights.title": "Review Insights",
  "guide.review-insights.prompt": "Analyze customer reviews for [product://target product] in [target market] using [file://exported review data]. Identify recurring complaints, unmet needs, purchase drivers, language patterns, and product or messaging opportunities. Quantify themes where possible and distinguish evidence from assumptions. If context is missing, ask an open follow-up question about useful reference information.",
  "guide.ugc-brief.title": "UGC Brief",
  "guide.ugc-brief.prompt": "Create a UGC video brief for [product://target product] on [platform] in [target market], aimed at [target audience], referencing [assets://model or visual style], and supporting [campaign goal] within [constraints]. Include key messages, filming guidelines, required shots, deliverables, and success criteria. If context is missing, ask an open follow-up question about useful campaign information.",
  "guide.video-scripts.title": "Video Scripts",
  "guide.video-scripts.prompt": "Write 10 short-form video scripts for [product://target product] on [platform], aimed at [target audience], incorporating [assets://character/actor], and reflecting [offer] and [tone]. Give each a strong hook, relatable scenario, product demonstration, proof point, and call to action, with enough creative variety for testing. If context is missing, ask an open follow-up question about useful creative information.",
  "guide.recreate-viral-ads.title": "Recreate Viral Ads",
  "guide.recreate-viral-ads.prompt": "Recreate this video using the selected clone mode and references.",
  "guide.search-terms.title": "Search Terms",
  "guide.search-terms.prompt": "Analyze [file://search term report] from [platform] for [date range], using [attribution settings] and [target metrics]. Identify high-performing queries, wasted ad spend, negative-keyword opportunities, and bid or budget actions. Separate data-backed findings from assumptions. If context is missing, ask an open follow-up question about useful report information.",
  "guide.roas-analysis.title": "ROAS Analysis",
  "guide.roas-analysis.prompt": "[file://ads report]\n\nAnalyze performance on [platform] for [date range] against [target ROAS/CPA], considering [attribution window] and [product://product margin]. Evaluate campaign, ad group or ad set, and ad-level spend, revenue, ROAS, CPA, CTR, CPC, and conversion rate; identify budget, audience, bidding, creative, and landing-page issues; and prioritize what to pause, scale, or test next. Distinguish data-backed findings from assumptions. If context is missing, ask an open follow-up question about useful report information.",
  "guide.unavailable": "The editor is not ready. Please retry shortly.",
  "guide.retry": "Retry",

  // Popular starters
  "guide.popular.title": "Popular Ways to Get Started",
  "guide.popular.marketing-insight.title": "Marketing Insight",
  "guide.popular.url-to-video.title": "URL to Video",
  "guide.popular.recreate-viral-ads.title": "Recreate Viral Ads",
  "guide.popular.bulk-create-ads.title": "Bulk Create Ads",
  "guide.popular.creative-presets.title": "Bulk Create Ads",
  "guide.popular.placeholder-notice": "This feature is coming soon!",

  // Marketing insight modal
  "guide.insight.modal.title": "Marketing Insight",
  "guide.insight.modal.subtitle": "Choose what you want to explore and add enough context for the agent to turn it into a focused marketing task.",
  "guide.insight.suggested": "Suggested for you",
  "guide.insight.explore.title": "What would you like to explore?",
  "guide.insight.start-btn": "Start insight →",
  "guide.insight.copied": "Copied to clipboard",
  "guide.insight.applied": "Draft applied to conversation input",

  // 6 Insight Items Title
  "guide.insight.tiktok-creators.title": "TikTok Creator & Influencer Research",
  "guide.insight.ads-roas.title": "Ads ROAS Analysis",
  "guide.insight.amazon-a-plus.title": "Amazon A+ Content Brief",
  "guide.insight.amazon-search-terms.title": "Amazon Search Term Report Analysis",
  "guide.insight.category-market.title": "Category Market Analysis",
  "guide.insight.title-optimization.title": "Product Listing Title Optimization",

  // 6 Insight Items Prompt (English)
  "guide.insight.tiktok-creators.prompt": "Find and shortlist TikTok creators for [product/brand] in [target market]. Evaluate audience fit, content style, engagement quality, brand safety, and collaboration potential, then recommend campaign roles and outreach angles. If context is missing, ask an open follow-up question about useful reference information.",
  "guide.insight.ads-roas.prompt": "[file://ads report]\n\nAnalyze performance on [platform] for [date range] against [target ROAS/CPA], considering [attribution window] and [product://product margin]. Evaluate campaign, ad group or ad set, and ad-level spend, revenue, ROAS, CPA, CTR, CPC, and conversion rate; identify budget, audience, bidding, creative, and landing-page issues; and prioritize what to pause, scale, or test next. Distinguish data-backed findings from assumptions. If context is missing, ask an open follow-up question about useful report information.",
  "guide.insight.amazon-a-plus.prompt": "Create an Amazon A+ Content brief for [product://target product], including the content structure, key messages, module recommendations, and visual direction. If context is missing, ask an open follow-up question about useful product information.",
  "guide.insight.amazon-search-terms.prompt": "Analyze [file://search term report] from [platform] for [date range], using [attribution settings] and [target metrics]. Identify high-performing queries, wasted ad spend, negative-keyword opportunities, and bid or budget actions. Separate data-backed findings from assumptions. If context is missing, ask an open follow-up question about useful report information.",
  "guide.insight.category-market.prompt": "Analyze the potential of [product category] on [ecommerce platform] in [target market]. Evaluate demand, competition, pricing, customer needs, barriers to entry, and growth signals; clearly distinguish facts, inferences, and assumptions; and recommend whether and how to enter. If context is missing, ask an open follow-up question about any useful reference information.",
  "guide.insight.title-optimization.prompt": "Optimize [current product title] for [ecommerce platform] using [product://product details]. Improve search visibility, keyword relevance, readability, differentiation, and conversion while following the platform’s requirements. Provide 3 recommended titles with concise rationales. If context is missing, ask an open follow-up question about useful product information.",

  // URL to Video modal
  "guide.url-to-video.modal.title": "URL to Video",
  "guide.url-to-video.modal.subtitle": "Turn a product page into a ready-to-run video ad.",
  "guide.url-to-video.product-url.label": "Product URL",
  "guide.url-to-video.product-url.placeholder": "Enter or paste a product page URL...",
  "guide.url-to-video.target-audience.label": "Target audience",
  "guide.url-to-video.target-audience.placeholder": "Who should this ad speak to?",
  "guide.url-to-video.key-selling-point.label": "Key selling point",
  "guide.url-to-video.key-selling-point.placeholder": "What benefit should stand out first?",
  "guide.url-to-video.visual-style.label": "Visual style",
  "guide.url-to-video.duration.label": "Duration",
  "guide.url-to-video.duration.auto": "Auto",
  "guide.url-to-video.duration.hint": "Let the model choose a natural length",
  "guide.url-to-video.aspect-ratio.label": "Aspect ratio",
  "guide.url-to-video.submit-btn": "Start creating →",
  "guide.url-to-video.url-required": "Please enter a product page URL first",
  "guide.url-to-video.applied": "Video ad draft applied to conversation input",

  // 9 Visual Styles (English)
  "guide.url-to-video.style.clean-studio": "Clean studio",
  "guide.url-to-video.style.cinematic-luxury": "Cinematic luxury",
  "guide.url-to-video.style.minimalist-premium": "Minimalist premium",
  "guide.url-to-video.style.natural-lifestyle": "Natural lifestyle",
  "guide.url-to-video.style.bold-colorful": "Bold & colorful",
  "guide.url-to-video.style.futuristic-tech": "Futuristic tech",
  "guide.url-to-video.style.ugc-style": "UGC style",
  "guide.url-to-video.style.unboxing": "Unboxing",
  "guide.url-to-video.style.street-style": "Street style",

  // Recreate Viral Ads modal
  "guide.recreate-viral-ads.modal.title": "Recreate Viral Ads",
  "guide.recreate-viral-ads.modal.subtitle": "Recreate video structure, or swap people and products while keeping the original idea.",
  "guide.recreate-viral-ads.clone-mode.label": "Clone mode",
  "guide.recreate-viral-ads.mode.recreate-structure.title": "Recreate structure",
  "guide.recreate-viral-ads.mode.recreate-structure.desc": "Keep the shots, pacing, and structure. Create new content.",
  "guide.recreate-viral-ads.mode.replace-elements.title": "Replace elements",
  "guide.recreate-viral-ads.mode.replace-elements.desc": "Swap people or products. Leave the rest unchanged.",
  "guide.recreate-viral-ads.target-video.label": "Target video",
  "guide.recreate-viral-ads.target-video.required": "REQUIRED",
  "guide.recreate-viral-ads.target-video.add": "Add target video",
  "guide.recreate-viral-ads.target-video.hint": "MP4 only · up to 50 MB · 2-60 seconds",
  "guide.recreate-viral-ads.prompt-input.label": "What should the new video show?",
  "guide.recreate-viral-ads.prompt-input.placeholder": "Describe the new subject, scenes, message, or elements to replace...",
  "guide.recreate-viral-ads.reference-materials.label": "Other reference materials",
  "guide.recreate-viral-ads.reference-materials.optional": "OPTIONAL",
  "guide.recreate-viral-ads.reference-materials.add": "Add other reference materials",
  "guide.recreate-viral-ads.reference-materials.hint": "Add product, character, brand, or visual references.",
  "guide.recreate-viral-ads.reference-materials.limit": "Up to 6 files",
  "guide.recreate-viral-ads.submit-btn": "Start creating →",
  "guide.recreate-viral-ads.video-required": "Please add a target video first",
  "guide.recreate-viral-ads.video-format-error": "Only MP4 video files are supported",
  "guide.recreate-viral-ads.video-size-error": "Video file size cannot exceed 50 MB",
  "guide.recreate-viral-ads.applied": "Viral ad recreation draft applied to conversation input",

  // Bulk Create Ads modal
  "guide.bulk-create-ads.modal.title": "Bulk Create Ads",
  "guide.bulk-create-ads.modal.subtitle": "Generate multiple ad variations with controlled format, duration, and creative angles.",
  "guide.bulk-create-ads.creative-brief.label": "Creative brief",
  "guide.bulk-create-ads.creative-brief.placeholder": "Describe the product, hook, benefits, and call to action...",
  "guide.bulk-create-ads.references.label": "References",
  "guide.bulk-create-ads.references.optional": "OPTIONAL",
  "guide.bulk-create-ads.references.add": "Add references",
  "guide.bulk-create-ads.references.hint": "Upload product photos, packaging, or short reference clips.",
  "guide.bulk-create-ads.references.limit": "Up to 6 files",
  "guide.bulk-create-ads.aspect-ratio.label": "Aspect ratio",
  "guide.bulk-create-ads.duration.label": "Duration",
  "guide.bulk-create-ads.video-count.label": "Number of videos",
  "guide.bulk-create-ads.video-count.desc": "Generate 1~10 variations from the same brief.",
  "guide.bulk-create-ads.submit-btn": "Generate creative plans →",
  "guide.bulk-create-ads.brief-required": "Please describe your creative brief first",
  "guide.bulk-create-ads.applied": "Bulk ad creation draft applied to conversation input",

  // Trending Videos, Ready to Replicate
  "guide.tabs.label": "Creation Discovery",
  "guide.tab.trending": "Inspiration",
  "guide.tab.skills": "Skill",
  "skills.subtitle": "Curated production skills, prefill prompt with one click to create.",
  "skills.category.all": "Featured",
  "skills.category.sk-commerce": "E-Commerce",
  "skills.category.sk-marketing": "Marketing",
  "skills.category.sk-office": "Productivity",
  "skills.category.sk-visual": "Visual & Video",
  "skills.category.sk-writing": "Content Creation",
  "skills.chips.label": "Skill categories",
  "skills.card.use": "Use Skill",
  "skills.source.badge": "Curated Workshop",
  "skills.empty": "No skills in this category.",
  "trending.title": "Trending Videos, Ready to Replicate",
  "trending.subtitle": "Pick viral structures worth cloning, then hand straight over to the composer.",
  "trending.source.badge": "From your inspiration library",
  "trending.source.hint": "Imported reference videos from the inspiration library, ranked by views.",
  "trending.filters.label": "Trending filters",
  "trending.filter.region": "Region",
  "trending.filter.industry": "Category",
  "trending.filter.views": "Video views",
  "trending.filter.engagement": "Engagement",
  "trending.filter.range": "Published within",
  "trending.filter.sort": "Sort",
  "trending.filter.reset": "Reset filters",
  "trending.region.all": "All regions",
  "trending.industry.all": "All categories",
  "trending.views.all": "Video views",
  "trending.views.100k": "100K+ views",
  "trending.views.1m": "1M+ views",
  "trending.views.5m": "5M+ views",
  "trending.views.10m": "10M+ views",
  "trending.engagement.all": "Engagement",
  "trending.engagement.0_5": "0.5%+ engagement",
  "trending.engagement.1": "1%+ engagement",
  "trending.engagement.2": "2%+ engagement",
  "trending.range.all": "Any published date",
  "trending.range.d7": "Published in 7 days",
  "trending.range.d30": "Published in 30 days",
  "trending.range.d90": "Published in 90 days",
  "trending.info.range": "Filters by publish date; items with no publish date are excluded from a date window.",
  "trending.sort.recommend": "Sort: Recommended",
  "trending.sort.views": "Sort: Video views",
  "trending.sort.engagement": "Sort: Engagement",
  "trending.info.engagement": "Total interactions divided by video views.",
  "trending.metric.engagement": "Engagement",
  "trending.metric.views": "Views",
  "trending.card.recreate": "Recreate",
  "trending.loading": "Reading reference videos from your inspiration library…",
  "trending.feed.loading": "Loading more reference videos…",
  "trending.feed.hint": "Keep scrolling to load more automatically",
  "trending.feed.end": "That is the whole library — every reference video is loaded",
  "trending.retry": "Retry",
  "trending.empty": "No reference video matches the current filters.",
  "trending.library.empty": "No reference video in your inspiration library yet.",
  "trending.library.emptyHint": "Import a reference video link in the inspiration library and it shows up here.",
  "trending.library.unavailable": "The inspiration library is not reachable right now.",
  "trending.library.unavailableHint": "Nothing is shown while the library is unavailable — no sample data stands in for it.",
  "trending.undock": "Restore composer",

  // Featured Skills bilingual titles and summaries
  "skills.locale": "en",
  "locale": "en",
  "skill.name.sk-omx-3d-animation-short-generator": "3D Animation Short Film",
  "skill.name.3d-animation-short-generator": "3D Animation Short Film",
  "skill.desc.sk-omx-3d-animation-short-generator": "Generate unified 3D animation shorts with character & scene setup, shot planning, and storyboard video synthesis.",
  "skill.desc.3d-animation-short-generator": "Generate unified 3D animation shorts with character & scene setup, shot planning, and storyboard video synthesis.",
  "skill.name.sk-omx-brand-promo-video-generator": "Brand Promo Video Generator",
  "skill.name.brand-promo-video-generator": "Brand Promo Video Generator",
  "skill.desc.sk-omx-brand-promo-video-generator": "Create presentation-ready brand promo videos with creative direction, storyboarding, and audiovisual synthesis.",
  "skill.desc.brand-promo-video-generator": "Create presentation-ready brand promo videos with creative direction, storyboarding, and audiovisual synthesis.",
  "skill.name.sk-omx-minimalist-product-ad-generator": "Minimalist Product Ad Generator",
  "skill.name.minimalist-product-ad-generator": "Minimalist Product Ad Generator",
  "skill.desc.sk-omx-minimalist-product-ad-generator": "Create clean, minimalist product commercial videos highlighting core selling points and aesthetics.",
  "skill.desc.minimalist-product-ad-generator": "Create clean, minimalist product commercial videos highlighting core selling points and aesthetics.",
  "skill.name.sk-omx-music-video-subtitle-generator": "Music Video Dynamic Subtitle Generator",
  "skill.name.music-video-subtitle-generator": "Music Video Dynamic Subtitle Generator",
  "skill.desc.sk-omx-music-video-subtitle-generator": "Synchronize dynamic rhythm-matched motion typography and stylized subtitles for AI music videos.",
  "skill.desc.music-video-subtitle-generator": "Synchronize dynamic rhythm-matched motion typography and stylized subtitles for AI music videos.",
  "skill.name.sk-omx-paper-collage-explainer-generator": "Paper Collage Explainer Animation",
  "skill.name.paper-collage-explainer-generator": "Paper Collage Explainer Animation",
  "skill.desc.sk-omx-paper-collage-explainer-generator": "Transform scripts and ideas into tactile, artistic paper collage stop-motion explainer animations.",
  "skill.desc.paper-collage-explainer-generator": "Transform scripts and ideas into tactile, artistic paper collage stop-motion explainer animations.",
  "skill.name.sk-omx-fpv-tour-video-generator": "FPV Tour Video Generator",
  "skill.name.fpv-tour-video-generator": "FPV Tour Video Generator",
  "skill.desc.sk-omx-fpv-tour-video-generator": "Generate thrilling, continuous first-person FPV drone one-take walkthroughs through 3D spaces.",
  "skill.desc.fpv-tour-video-generator": "Generate thrilling, continuous first-person FPV drone one-take walkthroughs through 3D spaces.",
  "skill.name.sk-omx-pov-short-film-generator": "POV Short Film Generator",
  "skill.name.pov-short-film-generator": "POV Short Film Generator",
  "skill.desc.sk-omx-pov-short-film-generator": "Direct immersive point-of-view (POV) cinematic short stories from the protagonist’s eyes.",
  "skill.desc.pov-short-film-generator": "Direct immersive point-of-view (POV) cinematic short stories from the protagonist’s eyes.",
  "skill.name.sk-omx-suspense-title-sequence-generator": "Suspense Film Title Sequence",
  "skill.name.suspense-title-sequence-generator": "Suspense Film Title Sequence",
  "skill.desc.sk-omx-suspense-title-sequence-generator": "Generate retro thriller and noir title sequences with atmospheric typography and moody lighting.",
  "skill.desc.suspense-title-sequence-generator": "Generate retro thriller and noir title sequences with atmospheric typography and moody lighting.",
  "skill.name.sk-amazon-keyword-traffic-analysis": "Amazon Keyword Traffic Analysis",
  "skill.name.amazon-keyword-traffic-analysis": "Amazon Keyword Traffic Analysis",
  "skill.desc.sk-amazon-keyword-traffic-analysis": "Amazon keyword, traffic source, ABA trend and PPC opportunity analysis.",
  "skill.desc.amazon-keyword-traffic-analysis": "Amazon keyword, traffic source, ABA trend and PPC opportunity analysis.",
  "skill.name.sk-amazon-listing-optimization": "Amazon Listing Optimization",
  "skill.name.amazon-listing-optimization": "Amazon Listing Optimization",
  "skill.desc.sk-amazon-listing-optimization": "Amazon listing, A+ and keyword coverage optimization.",
  "skill.desc.amazon-listing-optimization": "Amazon listing, A+ and keyword coverage optimization.",
  "skill.name.sk-amazon-market-analysis": "Amazon Market Analysis",
  "skill.name.amazon-market-analysis": "Amazon Market Analysis",
  "skill.desc.sk-amazon-market-analysis": "Amazon category and market opportunity analysis using amazon-mcp.",
  "skill.desc.amazon-market-analysis": "Amazon category and market opportunity analysis using amazon-mcp.",
  "skill.name.sk-amazon-product-analysis": "Amazon Product Analysis",
  "skill.name.amazon-product-analysis": "Amazon Product Analysis",
  "skill.desc.sk-amazon-product-analysis": "Amazon ASIN, SKU and competitor product research using amazon-mcp and files.",
  "skill.desc.amazon-product-analysis": "Amazon ASIN, SKU and competitor product research using amazon-mcp and files.",
  "skill.name.sk-amazon-review-optimization": "Amazon Review Optimization",
  "skill.name.amazon-review-optimization": "Amazon Review Optimization",
  "skill.desc.sk-amazon-review-optimization": "Amazon review, VOC, QA and pain-point optimization.",
  "skill.desc.amazon-review-optimization": "Amazon review, VOC, QA and pain-point optimization.",
  "skill.name.sk-amazon-trend-risk-monitor": "Amazon Trend Risk Monitor",
  "skill.name.amazon-trend-risk-monitor": "Amazon Trend Risk Monitor",
  "skill.desc.sk-amazon-trend-risk-monitor": "Amazon trend, BSR, sales prediction and trademark/risk monitoring.",
  "skill.desc.amazon-trend-risk-monitor": "Amazon trend, BSR, sales prediction and trademark/risk monitoring.",
  "skill.name.sk-bggg-data-amazon": "BGGG Amazon Data · Review Scraper",
  "skill.name.bggg-data-amazon": "BGGG Amazon Data · Review Scraper",
  "skill.desc.sk-bggg-data-amazon": "Collect public Amazon US reviews and normalize into auditable JSONL datasets for VOC.",
  "skill.desc.bggg-data-amazon": "Collect public Amazon US reviews and normalize into auditable JSONL datasets for VOC.",
  "skill.name.sk-ecommerce-daily-review": "Ecommerce Daily Review",
  "skill.name.ecommerce-daily-review": "Ecommerce Daily Review",
  "skill.desc.sk-ecommerce-daily-review": "Daily and weekly review template for Amazon and TikTok Shop operations.",
  "skill.desc.ecommerce-daily-review": "Daily and weekly review template for Amazon and TikTok Shop operations.",
  "skill.name.sk-ecommerce-output-spec": "Ecommerce Output Spec",
  "skill.name.ecommerce-output-spec": "Ecommerce Output Spec",
  "skill.desc.sk-ecommerce-output-spec": "Shared report and file output rules for ecommerce operation agents.",
  "skill.desc.ecommerce-output-spec": "Shared report and file output rules for ecommerce operation agents.",
  "skill.name.sk-ecommerce-routing-policy": "Ecommerce Routing Policy",
  "skill.name.ecommerce-routing-policy": "Ecommerce Routing Policy",
  "skill.desc.sk-ecommerce-routing-policy": "Shared routing rules for ecommerce operation agents.",
  "skill.desc.ecommerce-routing-policy": "Shared routing rules for ecommerce operation agents.",
  "skill.name.sk-html-report-templates": "HTML Report Templates",
  "skill.name.html-report-templates": "HTML Report Templates",
  "skill.desc.sk-html-report-templates": "Copy-and-fill HTML report and dashboard templates for html-writer.",
  "skill.desc.html-report-templates": "Copy-and-fill HTML report and dashboard templates for html-writer.",
  "skill.name.sk-omx-2d-animation-commentary-drama": "2D Animation Commentary Drama",
  "skill.name.2d-animation-commentary-drama": "2D Animation Commentary Drama",
  "skill.desc.sk-omx-2d-animation-commentary-drama": "Generate 2D anime commentary short dramas combining stylized visuals with dramatic voiceover.",
  "skill.desc.2d-animation-commentary-drama": "Generate 2D anime commentary short dramas combining stylized visuals with dramatic voiceover.",
  "skill.name.sk-omx-3d-comic-commentary-drama": "3D Comic Commentary Drama",
  "skill.name.3d-comic-commentary-drama": "3D Comic Commentary Drama",
  "skill.desc.sk-omx-3d-comic-commentary-drama": "Produce 3D dynamic webtoon commentary videos with choreographed action and character dialogue.",
  "skill.desc.3d-comic-commentary-drama": "Produce 3D dynamic webtoon commentary videos with choreographed action and character dialogue.",
  "skill.name.sk-omx-asmr-ambient": "ASMR Ambient Audio",
  "skill.name.asmr-ambient": "ASMR Ambient Audio",
  "skill.desc.sk-omx-asmr-ambient": "Generate sleep aid, meditation, and immersive ASMR ambient audio tracks.",
  "skill.desc.asmr-ambient": "Generate sleep aid, meditation, and immersive ASMR ambient audio tracks.",
  "skill.name.sk-omx-audiobook": "Multi-Voice Audiobook",
  "skill.name.audiobook": "Multi-Voice Audiobook",
  "skill.desc.sk-omx-audiobook": "Convert books and manuscripts into multi-character audiobooks with expressive narration.",
  "skill.desc.audiobook": "Convert books and manuscripts into multi-character audiobooks with expressive narration.",
  "skill.name.sk-omx-brand-stream-mg": "Brand Stream Motion Graphics",
  "skill.name.brand-stream-mg": "Brand Stream Motion Graphics",
  "skill.desc.sk-omx-brand-stream-mg": "Generate IP-led brand stream motion graphic videos for new product launches and social media buzz.",
  "skill.desc.brand-stream-mg": "Generate IP-led brand stream motion graphic videos for new product launches and social media buzz.",
  "skill.name.sk-omx-chinese-style-short-drama-generator": "Chinese Style Drama Generator",
  "skill.name.chinese-style-short-drama-generator": "Chinese Style Drama Generator",
  "skill.desc.sk-omx-chinese-style-short-drama-generator": "Full-pipeline production for traditional Chinese style cinematic short dramas.",
  "skill.desc.chinese-style-short-drama-generator": "Full-pipeline production for traditional Chinese style cinematic short dramas.",
  "skill.name.sk-omx-clip-export": "CapCut / JianYing Export",
  "skill.name.clip-export": "CapCut / JianYing Export",
  "skill.desc.sk-omx-clip-export": "Export and push ready-to-edit video projects directly into JianYing or CapCut drafts.",
  "skill.desc.clip-export": "Export and push ready-to-edit video projects directly into JianYing or CapCut drafts.",
  "skill.name.sk-omx-co-op-game-intro-generator": "Co-Op Game Intro Generator",
  "skill.name.co-op-game-intro-generator": "Co-Op Game Intro Generator",
  "skill.desc.sk-omx-co-op-game-intro-generator": "Generate stylized 2-player co-op game title and menu intro videos from character references.",
  "skill.desc.co-op-game-intro-generator": "Generate stylized 2-player co-op game title and menu intro videos from character references.",
  "skill.name.sk-omx-digital-product-promo-generator": "Digital Product Promo Video",
  "skill.name.digital-product-promo-generator": "Digital Product Promo Video",
  "skill.desc.sk-omx-digital-product-promo-generator": "Transform web apps, software interfaces, and UI motion into review-ready cinematic product promo videos.",
  "skill.desc.digital-product-promo-generator": "Transform web apps, software interfaces, and UI motion into review-ready cinematic product promo videos.",
  "skill.name.sk-omx-dot-matrix-brand-wordmark-motion": "Dot Matrix Wordmark Motion",
  "skill.name.dot-matrix-brand-wordmark-motion": "Dot Matrix Wordmark Motion",
  "skill.desc.sk-omx-dot-matrix-brand-wordmark-motion": "Generate futuristic dot-matrix wordmark motion videos and branding graphics from logos and slogans.",
  "skill.desc.dot-matrix-brand-wordmark-motion": "Generate futuristic dot-matrix wordmark motion videos and branding graphics from logos and slogans.",
  "skill.name.sk-omx-drama-soundtrack": "Drama Soundtrack Composer",
  "skill.name.drama-soundtrack": "Drama Soundtrack Composer",
  "skill.desc.sk-omx-drama-soundtrack": "Compose emotive character theme songs and immersive background soundtracks for films and dramas.",
  "skill.desc.drama-soundtrack": "Compose emotive character theme songs and immersive background soundtracks for films and dramas.",
  "skill.name.sk-omx-ecommerce-design": "E-Commerce Graphic Design",
  "skill.name.ecommerce-design": "E-Commerce Graphic Design",
  "skill.desc.sk-omx-ecommerce-design": "Design conversion-focused e-commerce product detail pages, hero banners, and promotional cards.",
  "skill.desc.ecommerce-design": "Design conversion-focused e-commerce product detail pages, hero banners, and promotional cards.",
  "skill.name.sk-omx-ecommerce-image": "E-Commerce Product Image",
  "skill.name.ecommerce-image": "E-Commerce Product Image",
  "skill.desc.sk-omx-ecommerce-image": "Generate platform-compliant, commercial-grade product photography sets from real product shots.",
  "skill.desc.ecommerce-image": "Generate platform-compliant, commercial-grade product photography sets from real product shots.",
  "skill.name.sk-omx-education-studio": "Education Content Studio",
  "skill.name.education-studio": "Education Content Studio",
  "skill.desc.sk-omx-education-studio": "All-in-one studio for instructional content, explainer videos, courseware, and learning materials.",
  "skill.desc.education-studio": "All-in-one studio for instructional content, explainer videos, courseware, and learning materials.",
  "skill.name.sk-omx-fashion-scene-showcase-video": "Fashion Scene Showcase Video",
  "skill.name.fashion-scene-showcase-video": "Fashion Scene Showcase Video",
  "skill.desc.sk-omx-fashion-scene-showcase-video": "Generate high-fashion runway walks and editorial streetwear showcase videos with realistic drape.",
  "skill.desc.fashion-scene-showcase-video": "Generate high-fashion runway walks and editorial streetwear showcase videos with realistic drape.",
  "skill.name.sk-omx-felt-stop-motion-story-short": "Felt Stop-Motion Story Short",
  "skill.name.felt-stop-motion-story-short": "Felt Stop-Motion Story Short",
  "skill.desc.sk-omx-felt-stop-motion-story-short": "Produce cozy felt needlecraft stop-motion stories featuring soft fabric textures and fairytale charm.",
  "skill.desc.felt-stop-motion-story-short": "Produce cozy felt needlecraft stop-motion stories featuring soft fabric textures and fairytale charm.",
  "skill.name.sk-omx-film-reference-prompt-writer": "Cinematic Prompt Master",
  "skill.name.film-reference-prompt-writer": "Cinematic Prompt Master",
  "skill.desc.sk-omx-film-reference-prompt-writer": "Extract lighting, lenses, and composition rules from movie references into high-precision production prompts.",
  "skill.desc.film-reference-prompt-writer": "Extract lighting, lenses, and composition rules from movie references into high-precision production prompts.",
  "skill.name.sk-omx-h3-prompt-expert": "H3 Video Prompt Expert",
  "skill.name.h3-prompt-expert": "H3 Video Prompt Expert",
  "skill.desc.sk-omx-h3-prompt-expert": "Turn loose creative ideas and media references into structured, high-control multimodal video prompts.",
  "skill.desc.h3-prompt-expert": "Turn loose creative ideas and media references into structured, high-control multimodal video prompts.",
  "skill.name.sk-omx-h3-visual-design": "H3 Visual Motion Design",
  "skill.name.h3-visual-design": "H3 Visual Motion Design",
  "skill.desc.sk-omx-h3-visual-design": "Professional motion typography, dynamic packaging, and spatial graphic visual effects.",
  "skill.desc.h3-visual-design": "Professional motion typography, dynamic packaging, and spatial graphic visual effects.",
  "skill.name.sk-omx-handdrawn-live-video-generator": "Hand-Drawn & Live Fusion Video",
  "skill.name.handdrawn-live-video-generator": "Hand-Drawn & Live Fusion Video",
  "skill.desc.sk-omx-handdrawn-live-video-generator": "Blend 2D hand-drawn doodle animation seamlessly with live-action footage for creative viral clips.",
  "skill.desc.handdrawn-live-video-generator": "Blend 2D hand-drawn doodle animation seamlessly with live-action footage for creative viral clips.",
  "skill.name.sk-omx-ip-toy-grid-motion": "IP Toy 6-Grid Motion Poster",
  "skill.name.ip-toy-grid-motion": "IP Toy 6-Grid Motion Poster",
  "skill.desc.sk-omx-ip-toy-grid-motion": "Turn character designs into dynamic 3D collectible toy 6-grid motion posters for social media.",
  "skill.desc.ip-toy-grid-motion": "Turn character designs into dynamic 3D collectible toy 6-grid motion posters for social media.",
  "skill.name.sk-omx-line-doodle-explainer-generator": "Line Doodle Explainer Video",
  "skill.name.line-doodle-explainer-generator": "Line Doodle Explainer Video",
  "skill.desc.sk-omx-line-doodle-explainer-generator": "Generate fun line-doodle explainer videos and storyboard assets from educational concepts.",
  "skill.desc.line-doodle-explainer-generator": "Generate fun line-doodle explainer videos and storyboard assets from educational concepts.",
  "skill.name.sk-omx-lip-product-ad-generator": "Lipstick & Lip Product Ad",
  "skill.name.lip-product-ad-generator": "Lipstick & Lip Product Ad",
  "skill.desc.sk-omx-lip-product-ad-generator": "Produce luxury commercial TVC videos for lipstick and cosmetic beauty products.",
  "skill.desc.lip-product-ad-generator": "Produce luxury commercial TVC videos for lipstick and cosmetic beauty products.",
  "skill.name.sk-omx-live-action-commentary-drama": "Live-Action Commentary Drama",
  "skill.name.live-action-commentary-drama": "Live-Action Commentary Drama",
  "skill.desc.sk-omx-live-action-commentary-drama": "Craft high-retention live-action drama recaps with instant hook voiceovers and rapid pacing.",
  "skill.desc.live-action-commentary-drama": "Craft high-retention live-action drama recaps with instant hook voiceovers and rapid pacing.",
  "skill.name.sk-omx-micro-expression-video-generator": "Micro-Expression Video Generator",
  "skill.name.micro-expression-video-generator": "Micro-Expression Video Generator",
  "skill.desc.sk-omx-micro-expression-video-generator": "Design nuanced facial micro-expressions and emotional shifts for photorealistic character acting.",
  "skill.desc.micro-expression-video-generator": "Design nuanced facial micro-expressions and emotional shifts for photorealistic character acting.",
  "skill.name.sk-omx-papercraft-stop-motion-explainer": "Papercraft Stop-Motion Explainer",
  "skill.name.papercraft-stop-motion-explainer": "Papercraft Stop-Motion Explainer",
  "skill.desc.sk-omx-papercraft-stop-motion-explainer": "Craft whimsical paper cutout puppets, layered stages, and stop-motion educational explainer videos.",
  "skill.desc.papercraft-stop-motion-explainer": "Craft whimsical paper cutout puppets, layered stages, and stop-motion educational explainer videos.",
  "skill.name.sk-omx-product-kinetic-typography-tvc": "Kinetic Typography Product TVC",
  "skill.name.product-kinetic-typography-tvc": "Kinetic Typography Product TVC",
  "skill.desc.sk-omx-product-kinetic-typography-tvc": "Generate high-energy commercial TVCs merging 3D kinetic typography tracked to moving products.",
  "skill.desc.product-kinetic-typography-tvc": "Generate high-energy commercial TVCs merging 3D kinetic typography tracked to moving products.",
  "skill.name.sk-omx-retro-city-cel-animation-short": "Retro City Cel Animation Short",
  "skill.name.retro-city-cel-animation-short": "Retro City Cel Animation Short",
  "skill.desc.sk-omx-retro-city-cel-animation-short": "Create 90s vintage anime cel animation clips bathed in neon nostalgia and City Pop aesthetic.",
  "skill.desc.retro-city-cel-animation-short": "Create 90s vintage anime cel animation clips bathed in neon nostalgia and City Pop aesthetic.",
  "skill.name.sk-omx-scifi-cinematic-video-generator": "Sci-Fi Cinematic Video Generator",
  "skill.name.scifi-cinematic-video-generator": "Sci-Fi Cinematic Video Generator",
  "skill.desc.sk-omx-scifi-cinematic-video-generator": "Render epic cyberpunk and hard sci-fi cinematic footage with volumetric fog and intricate mechanical detail.",
  "skill.desc.scifi-cinematic-video-generator": "Render epic cyberpunk and hard sci-fi cinematic footage with volumetric fog and intricate mechanical detail.",
  "skill.name.sk-omx-short-drama-multilingual-dubbing": "Short Drama Multilingual Dubbing",
  "skill.name.short-drama-multilingual-dubbing": "Short Drama Multilingual Dubbing",
  "skill.desc.sk-omx-short-drama-multilingual-dubbing": "Localize drama clips into multiple languages with voice clone preservation and synchronized captions.",
  "skill.desc.short-drama-multilingual-dubbing": "Localize drama clips into multiple languages with voice clone preservation and synchronized captions.",
  "skill.name.sk-omx-short-drama-screenwriter": "Short Drama Screenwriter Assistant",
  "skill.name.short-drama-screenwriter": "Short Drama Screenwriter Assistant",
  "skill.desc.sk-omx-short-drama-screenwriter": "Write high-tension, fast-paced episodic drama scripts optimized for short video platforms.",
  "skill.desc.short-drama-screenwriter": "Write high-tension, fast-paced episodic drama scripts optimized for short video platforms.",
  "skill.name.sk-omx-short-drama-series-writer": "Micro-Drama Series Writer",
  "skill.name.short-drama-series-writer": "Micro-Drama Series Writer",
  "skill.desc.sk-omx-short-drama-series-writer": "Develop full episodic series bibles, cliffhangers, and character arcs for serialized micro-dramas.",
  "skill.desc.short-drama-series-writer": "Develop full episodic series bibles, cliffhangers, and character arcs for serialized micro-dramas.",
  "skill.name.sk-omx-silkscreen-decorative-illustration-short": "Silkscreen Illustration Short Video",
  "skill.name.silkscreen-decorative-illustration-short": "Silkscreen Illustration Short Video",
  "skill.desc.sk-omx-silkscreen-decorative-illustration-short": "Animate silkscreen decorative prints and vintage graphics into elegant luxury aesthetic video ads.",
  "skill.desc.silkscreen-decorative-illustration-short": "Animate silkscreen decorative prints and vintage graphics into elegant luxury aesthetic video ads.",
  "skill.name.sk-omx-sitcom-story-video-generator": "Sitcom Story Video Generator",
  "skill.name.sitcom-story-video-generator": "Sitcom Story Video Generator",
  "skill.desc.sk-omx-sitcom-story-video-generator": "Generate multi-cam episodic sitcom story clips complete with humorous timing and banter.",
  "skill.desc.sitcom-story-video-generator": "Generate multi-cam episodic sitcom story clips complete with humorous timing and banter.",
  "skill.name.sk-omx-subtitle-correction": "SRT Subtitle Correction",
  "skill.name.subtitle-correction": "SRT Subtitle Correction",
  "skill.desc.sk-omx-subtitle-correction": "Fix ASR transcript typos, homophones, and terminology while preserving exact SRT timing.",
  "skill.desc.subtitle-correction": "Fix ASR transcript typos, homophones, and terminology while preserving exact SRT timing.",
  "skill.name.sk-omx-transcript-broll-planner": "Talking Head B-Roll Planner",
  "skill.name.transcript-broll-planner": "Talking Head B-Roll Planner",
  "skill.desc.sk-omx-transcript-broll-planner": "Break speaking scripts into scene-by-scene B-roll visual lists and generate complementary video footage.",
  "skill.desc.transcript-broll-planner": "Break speaking scripts into scene-by-scene B-roll visual lists and generate complementary video footage.",
  "skill.name.sk-omx-video-deconstruct": "Video Deconstruction & Replication",
  "skill.name.video-deconstruct": "Video Deconstruction & Replication",
  "skill.desc.sk-omx-video-deconstruct": "Reverse-engineer reference videos into shot-by-shot prompt recipes and reproducible editing blueprints.",
  "skill.desc.video-deconstruct": "Reverse-engineer reference videos into shot-by-shot prompt recipes and reproducible editing blueprints.",
  "skill.name.sk-omx-video-deconstruct-analyzer": "Video Deconstruction Analyst",
  "skill.name.video-deconstruct-analyzer": "Video Deconstruction Analyst",
  "skill.desc.sk-omx-video-deconstruct-analyzer": "Deeply analyze AI-generated video rhythm, camera movements, prompt dynamics, and audio cues.",
  "skill.desc.video-deconstruct-analyzer": "Deeply analyze AI-generated video rhythm, camera movements, prompt dynamics, and audio cues.",
  "skill.name.sk-omx-vox-style-video-generator": "Vox-Style Explainer Animation",
  "skill.name.vox-style-video-generator": "Vox-Style Explainer Animation",
  "skill.desc.sk-omx-vox-style-video-generator": "Create iconic Vox-style collage documentary explainer animations with maps, photos, and animated charts.",
  "skill.desc.vox-style-video-generator": "Create iconic Vox-style collage documentary explainer animations with maps, photos, and animated charts.",
  "skill.name.sk-omx-wes-anderson-aesthetic-generator": "Wes Anderson Aesthetic Generator",
  "skill.name.wes-anderson-aesthetic-generator": "Wes Anderson Aesthetic Generator",
  "skill.desc.sk-omx-wes-anderson-aesthetic-generator": "Produce distinctive Wes Anderson style videos with symmetrical framing, pastel palettes, and whip pans.",
  "skill.desc.wes-anderson-aesthetic-generator": "Produce distinctive Wes Anderson style videos with symmetrical framing, pastel palettes, and whip pans.",
  "skill.name.sk-shopee-brand-analysis": "Shopee Brand Analysis",
  "skill.name.shopee-brand-analysis": "Shopee Brand Analysis",
  "skill.desc.sk-shopee-brand-analysis": "Shopee brand ranking, detail, trend, assortment and site/category distribute using shopee-mcp.",
  "skill.desc.shopee-brand-analysis": "Shopee brand ranking, detail, trend, assortment and site/category distribute using shopee-mcp.",
  "skill.name.sk-shopee-keyword-analysis": "Shopee Keyword Analysis",
  "skill.name.shopee-keyword-analysis": "Shopee Keyword Analysis",
  "skill.desc.sk-shopee-keyword-analysis": "Shopee hot-search word ranking, detail, trend and related items using shopee-mcp.",
  "skill.desc.shopee-keyword-analysis": "Shopee hot-search word ranking, detail, trend and related items using shopee-mcp.",
  "skill.name.sk-shopee-market-analysis": "Shopee Market Analysis",
  "skill.name.shopee-market-analysis": "Shopee Market Analysis",
  "skill.desc.sk-shopee-market-analysis": "Shopee site and category market opportunity analysis using shopee-mcp.",
  "skill.desc.shopee-market-analysis": "Shopee site and category market opportunity analysis using shopee-mcp.",
  "skill.name.sk-shopee-product-analysis": "Shopee Product Analysis",
  "skill.name.shopee-product-analysis": "Shopee Product Analysis",
  "skill.desc.sk-shopee-product-analysis": "Shopee item ranking, detail, trend and hot-word analysis using shopee-mcp.",
  "skill.desc.shopee-product-analysis": "Shopee item ranking, detail, trend and hot-word analysis using shopee-mcp.",
  "skill.name.sk-shopee-shop-analysis": "Shopee Shop Analysis",
  "skill.name.shopee-shop-analysis": "Shopee Shop Analysis",
  "skill.desc.sk-shopee-shop-analysis": "Shopee shop ranking, detail, trend, assortment and brand mix analysis using shopee-mcp.",
  "skill.desc.shopee-shop-analysis": "Shopee shop ranking, detail, trend, assortment and brand mix analysis using shopee-mcp.",
  "skill.name.sk-tiktok-market-trend-analysis": "TikTok Market Trend Analysis",
  "skill.name.tiktok-market-trend-analysis": "TikTok Market Trend Analysis",
  "skill.desc.sk-tiktok-market-trend-analysis": "TikTok Shop region, category, item and seller trend analysis using Topview td tools.",
  "skill.desc.tiktok-market-trend-analysis": "TikTok Shop region, category, item and seller trend analysis using Topview td tools.",
  "skill.name.sk-tiktok-material-breakdown": "TikTok Material Breakdown",
  "skill.name.tiktok-material-breakdown": "TikTok Material Breakdown",
  "skill.desc.sk-tiktok-material-breakdown": "TikTok viral video, material, hook and CTA breakdown.",
  "skill.desc.tiktok-material-breakdown": "TikTok viral video, material, hook and CTA breakdown.",
  "skill.name.sk-tiktok-product-selection": "TikTok Product Selection",
  "skill.name.tiktok-product-selection": "TikTok Product Selection",
  "skill.desc.sk-tiktok-product-selection": "TikTok Shop viral product selection and scoring.",
  "skill.desc.tiktok-product-selection": "TikTok Shop viral product selection and scoring.",
  "skill.name.sk-tiktok-script-creation": "TikTok Script Creation",
  "skill.name.tiktok-script-creation": "TikTok Script Creation",
  "skill.desc.sk-tiktok-script-creation": "TikTok UGC, creator, ad and live script generation.",
  "skill.desc.tiktok-script-creation": "TikTok UGC, creator, ad and live script generation.",
  "skill.name.sk-video-generate-canvas": "video-generate-canvas",
  "skill.name.video-generate-canvas": "video-generate-canvas",
  "skill.desc.sk-video-generate-canvas": "Trigger this skill whenever the user expresses any intent to create video content, such as generating videos or editing on canvas.",
  "skill.desc.video-generate-canvas": "Trigger this skill whenever the user expresses any intent to create video content, such as generating videos or editing on canvas.",
}
