/** Topview AI Marketer quick actions, captured 2026-09-09; draft-only. */
export const STARTER_GROUPS = ['market-insights', 'listing-reviews', 'content-creators', 'ad-analytics']
export const STARTERS = [
  { id: 'category-opportunity', group: 'market-insights', icon: 'chart-column' },
  { id: 'trending-products', group: 'market-insights', icon: 'chart-column' },
  { id: 'competitor-scan', group: 'market-insights', icon: 'chart-column' },
  { id: 'title-optimization', group: 'listing-reviews', icon: 'file-pen' },
  { id: 'review-insights', group: 'listing-reviews', icon: 'message-square-text' },
  { id: 'ugc-brief', group: 'content-creators', icon: 'clapperboard' },
  { id: 'video-scripts', group: 'content-creators', icon: 'clapperboard' },
  { id: 'recreate-viral-ads', group: 'content-creators', icon: 'wand-sparkles' },
  { id: 'search-terms', group: 'ad-analytics', icon: 'chart-column' },
  { id: 'roas-analysis', group: 'ad-analytics', icon: 'chart-line' },
]

export const guideZh = {
  "guide.title": "开始一个营销任务",
  "guide.market-insights": "市场洞察",
  "guide.listing-reviews": "列表和评论",
  "guide.content-creators": "内容与创作者",
  "guide.ad-analytics": "广告分析",
  "guide.category-opportunity.title": "品类机会",
  "guide.category-opportunity.prompt": "Analyze the potential of [product category] on [ecommerce platform] in [target market]. Evaluate demand, competition, pricing, customer needs, barriers to entry, and growth signals; clearly distinguish facts, inferences, and assumptions; and recommend whether and how to enter. If context is missing, ask an open follow-up question about any useful reference information.",
  "guide.trending-products.title": "热门产品",
  "guide.trending-products.prompt": "Identify trending products with strong sales potential in [category] on [ecommerce platform] in [target market], taking [business context or constraints] into account. Explain the demand signals, audience fit, competitive intensity, pricing opportunity, seasonality, and operational risks behind each recommendation. If context is missing, ask an open follow-up question about useful reference information.",
  "guide.competitor-scan.title": "竞争对手扫描",
  "guide.competitor-scan.prompt": "Analyze the top-ranking competitor product listings for [keyword/category] on [ecommerce platform] in [target market]. Compare positioning, pricing, offers, reviews, content, selling points, and conversion tactics, then identify specific opportunities for differentiation. If context is missing, ask an open follow-up question about useful reference information.",
  "guide.title-optimization.title": "标题优化",
  "guide.title-optimization.prompt": "Optimize [current product title] for [ecommerce platform] using [product details or target keywords]. Improve search visibility, keyword relevance, readability, differentiation, and conversion while following the platform’s requirements. Provide the recommended title with a concise rationale. If context is missing, ask an open follow-up question about useful product information.",
  "guide.review-insights.title": "评论洞察",
  "guide.review-insights.prompt": "Analyze customer reviews for [product/listing] in [target market] using [review source or exported review data]. Identify recurring complaints, unmet needs, purchase drivers, language patterns, and product or messaging opportunities. Quantify themes where possible and distinguish evidence from assumptions. If context is missing, ask an open follow-up question about useful reference information.",
  "guide.ugc-brief.title": "UGC 简报",
  "guide.ugc-brief.prompt": "Create a UGC video brief for [product] on [platform] in [target market], aimed at [target audience] and supporting [campaign goal] within [constraints]. Include key messages, filming guidelines, required shots, deliverables, and success criteria. If context is missing, ask an open follow-up question about useful campaign information.",
  "guide.video-scripts.title": "视频脚本",
  "guide.video-scripts.prompt": "Write 10 short-form video scripts for [product] on [platform], aimed at [target audience] and reflecting [offer] and [tone]. Give each a strong hook, relatable scenario, product demonstration, proof point, and call to action, with enough creative variety for testing. If context is missing, ask an open follow-up question about useful creative information.",
  "guide.recreate-viral-ads.title": "复制病毒式广告",
  "guide.recreate-viral-ads.prompt": "Recreate this video using the selected clone mode and references.",
  "guide.search-terms.title": "搜索词",
  "guide.search-terms.prompt": "Analyze [uploaded search term report] from [platform] for [date range], using [attribution settings] and [target metrics]. Identify high-performing queries, wasted ad spend, negative-keyword opportunities, and bid or budget actions. Separate data-backed findings from assumptions. If context is missing, ask an open follow-up question about useful report information.",
  "guide.roas-analysis.title": "广告支出回报率分析",
  "guide.roas-analysis.prompt": "[Drop or upload your Ads report in CSV or XLSX format]\n\nAnalyze performance on [platform] for [date range] against [target ROAS/CPA], considering [attribution window] and [product margin]. Evaluate campaign, ad group or ad set, and ad-level spend, revenue, ROAS, CPA, CTR, CPC, and conversion rate; identify budget, audience, bidding, creative, and landing-page issues; and prioritize what to pause, scale, or test next. Distinguish data-backed findings from assumptions. If context is missing, ask an open follow-up question about useful report information.",
  'guide.unavailable': '输入框尚未准备好，请稍后重试。',
  'guide.retry': '重试',
}

export const guideEn = {
  "guide.title": "Start a marketing task",
  "guide.market-insights": "Market Insights",
  "guide.listing-reviews": "Listing & Reviews",
  "guide.content-creators": "Content & Creators",
  "guide.ad-analytics": "Ad Analytics",
  "guide.category-opportunity.title": "Category Opportunity",
  "guide.category-opportunity.prompt": "Analyze the potential of [product category] on [ecommerce platform] in [target market]. Evaluate demand, competition, pricing, customer needs, barriers to entry, and growth signals; clearly distinguish facts, inferences, and assumptions; and recommend whether and how to enter. If context is missing, ask an open follow-up question about any useful reference information.",
  "guide.trending-products.title": "Trending Products",
  "guide.trending-products.prompt": "Identify trending products with strong sales potential in [category] on [ecommerce platform] in [target market], taking [business context or constraints] into account. Explain the demand signals, audience fit, competitive intensity, pricing opportunity, seasonality, and operational risks behind each recommendation. If context is missing, ask an open follow-up question about useful reference information.",
  "guide.competitor-scan.title": "Competitor Scan",
  "guide.competitor-scan.prompt": "Analyze the top-ranking competitor product listings for [keyword/category] on [ecommerce platform] in [target market]. Compare positioning, pricing, offers, reviews, content, selling points, and conversion tactics, then identify specific opportunities for differentiation. If context is missing, ask an open follow-up question about useful reference information.",
  "guide.title-optimization.title": "Title Optimization",
  "guide.title-optimization.prompt": "Optimize [current product title] for [ecommerce platform] using [product details or target keywords]. Improve search visibility, keyword relevance, readability, differentiation, and conversion while following the platform’s requirements. Provide the recommended title with a concise rationale. If context is missing, ask an open follow-up question about useful product information.",
  "guide.review-insights.title": "Review Insights",
  "guide.review-insights.prompt": "Analyze customer reviews for [product/listing] in [target market] using [review source or exported review data]. Identify recurring complaints, unmet needs, purchase drivers, language patterns, and product or messaging opportunities. Quantify themes where possible and distinguish evidence from assumptions. If context is missing, ask an open follow-up question about useful reference information.",
  "guide.ugc-brief.title": "UGC Brief",
  "guide.ugc-brief.prompt": "Create a UGC video brief for [product] on [platform] in [target market], aimed at [target audience] and supporting [campaign goal] within [constraints]. Include key messages, filming guidelines, required shots, deliverables, and success criteria. If context is missing, ask an open follow-up question about useful campaign information.",
  "guide.video-scripts.title": "Video Scripts",
  "guide.video-scripts.prompt": "Write 10 short-form video scripts for [product] on [platform], aimed at [target audience] and reflecting [offer] and [tone]. Give each a strong hook, relatable scenario, product demonstration, proof point, and call to action, with enough creative variety for testing. If context is missing, ask an open follow-up question about useful creative information.",
  "guide.recreate-viral-ads.title": "Recreate Viral Ads",
  "guide.recreate-viral-ads.prompt": "Recreate this video using the selected clone mode and references.",
  "guide.search-terms.title": "Search Terms",
  "guide.search-terms.prompt": "Analyze [uploaded search term report] from [platform] for [date range], using [attribution settings] and [target metrics]. Identify high-performing queries, wasted ad spend, negative-keyword opportunities, and bid or budget actions. Separate data-backed findings from assumptions. If context is missing, ask an open follow-up question about useful report information.",
  "guide.roas-analysis.title": "ROAS Analysis",
  "guide.roas-analysis.prompt": "[Drop or upload your Ads report in CSV or XLSX format]\n\nAnalyze performance on [platform] for [date range] against [target ROAS/CPA], considering [attribution window] and [product margin]. Evaluate campaign, ad group or ad set, and ad-level spend, revenue, ROAS, CPA, CTR, CPC, and conversion rate; identify budget, audience, bidding, creative, and landing-page issues; and prioritize what to pause, scale, or test next. Distinguish data-backed findings from assumptions. If context is missing, ask an open follow-up question about useful report information.",
  'guide.unavailable': 'The editor is not ready. Please retry shortly.',
  'guide.retry': 'Retry',
}
